### ISSUE TITLE
Create a template construction

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#125]
{m:template <nameExpression>}
{m:endtemplate}

and create an AQL IService allowing to call such template

**Comment by ylussaud** [comment]
This will allow recursion.

**Comment by phdesanois** [comment]
This enhancement will be very useful for real documentation production . Templates documents will be smaller, easier to write and especially to maintain.
Regarding our templates documents, this tag will reduce their size more than 40%.

**Comment by ylussaud** [comment]
The core part of this implementation should be in AQL. This mean we need to create an extra release of AQL (probably 6.1.0) with lookup helpers.

We need to add two custom properties to import and extend other templates (modules?).
The terminology should be changed:
* templates (the .docx file) should be called modules
* the new template construction should be called template

The idea here is to reflect the terminology of Acceleo.

**Comment by ylussaud** [comment]
Issue #246 should be done before starting working on this.

**Comment by ylussaud** [comment]
A first version is available in version 2.0.0 see the [documentation](http://www.m2doc.org/ref-doc/nightly/index.html#template-construct-example).

**Comment by ylussaud** [comment]
done
