### ISSUE TITLE
The template configuration dialog doesn't provide enough details on the configuration errors

### ISSUE THREAD

**Issue by RomainGuider** [ObeoNetwork/M2Doc#128]
When a variable has a wrong type name (for instance string instead of String) the dialog indicates there's a problem but doesn't give a clue on what the problem is. 

This is quite confusing although the problem essentially arise with templates that were configured by hand because the current dialog won't let you write 'string' instead of 'String'.

**Comment by ylussaud** [comment]
I think this issue is fixed by the validation of template. An error message will be added when using the variable.
