### ISSUE TITLE
Validation message doesn't report the fact that errors have been found in the template

### ISSUE THREAD

**Issue by RomainGuider** [ObeoNetwork/M2Doc#129]
When validating a template with errors, the dialog doesn't reports that errors have been found. The message the popped dialog provides is 'the validation has been performed successfuly'. 

This is misleading and an error dialog should pop instead when errors have been found.

**Comment by ylussaud** [comment]
When using the "Validate document template" Eclipse command the dialog says:

"Error(s) detected during validation. A log file has been generated next the the template file."

I don't know when this has been changed, but it looks like this issue is fixed.
