### ISSUE TITLE
[Specification] Parsing validation

### ISSUE THREAD

**Issue by pguilet** [ObeoNetwork/M2Doc#13]
We want to be able to validate syntactically a template to be sur it will produce the wanted result without being polluted by generation errors.

To do that, we will have a validation function that wil annotate the original template in a copy with error message for each parsing error encountered.
The validated document (the copy) will be pust in the same folder as the template validated.
The annotation will be some text with a specific style very distinguishable : 

![styleerrormessage](https://cloud.githubusercontent.com/assets/1279966/16681005/904a7b9e-44f2-11e6-9ce7-c7de7384453f.png)

We choose to use a font in 16px because most of standard text will be around 11-12px. So it will be easier to identify the error message among legit word and template content.
We also use a text in red associated to error message and a grey background to have contrast with the rest of the document that will not have background in most cases to identify again with more ease if texts come from parsing errors.

The position of the error message in the document will depend of the kind of problem. 
Indeed the purpose of inserted the error message in the template is to be able to see were the problem is located in the quicliest way possible.

If the problem is located in a start tag or a simple tag, the error message will be put just next to it on the right : 
![simpleandstarttagerrors](https://cloud.githubusercontent.com/assets/1279966/16617400/c7ca39a8-4383-11e6-81f9-fd41682ef804.png)
We don't put error message next to end tags because the end tag can be out of view of the start tag. So if the problem is located in the start tag, then it would be difficult to locate it quickly.

The other kind of parsing errors we can have is the presence of an end tag whereas either a corresponding start tag is missing or the precedent start tag is not of the kind of the end tag. 
In this case, we will show the error just next to the forbidden end tag :    
![endtagparsingerror](https://cloud.githubusercontent.com/assets/1279966/16681100/1497af0c-44f3-11e6-8824-5e31ce4f31d7.png)

In case of multiple parsing errors, they will be put next to the other separated by four spaces : 
![multierror](https://cloud.githubusercontent.com/assets/1279966/16680971/676d7f96-44f2-11e6-8188-f2b39b84e7a0.png)

**Comment by nlepine** [comment]
fix in 0.9.1
