### ISSUE TITLE
When using Sirius integration the model management (more especially loading) should be delegated to Sirius

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/M2Doc#141]
The primary use case is: being able to use M2doc with Sirius based tooling which already uses some of the model management APIs that are provided by Sirius. Capella is such an example with a model which rely on the initialization of setup of a specific ResourceSet, editing domain, and Session. Without such a delegation the diagrams might not be conform to what the user expect or derived references might return wrong results.

**Comment by ylussaud** [comment]
Do you have an entry point in Sirius to achieve this ?

**Comment by cbrun** [comment]
You will need an URI to the .aird filet then `SessionFactory.INSTANCE.createSession(URI sessionResourceURI, IProgressMonitor monitor) should get you a  session instance, from this `session.open(monitor)` and you can retrieve the resource set through session.getTransactionalEditingDomain().getResourceSet()
