### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by AlawnWong** [ObeoNetwork/M2Doc#160]
How to install ?

**Comment by ylussaud** [comment]
If you want to use it inside Eclipse you can use the last release p2 repository:

https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/M2Doc_0.9.9/repository

you can add the repository in the Eclipse Help/Install new software/... menu. I don't know the GUI status for launching a generation but If you plan yo use it programmatically you can use the source repository and have a look at https://github.com/ObeoNetwork/M2Doc/blob/master/plugins/org.obeonetwork.m2doc/src/org/obeonetwork/m2doc/util/M2DocUtils.java

M2DocUtils.parse(URI templateURI, IQueryEnvironment queryEnvironment)
M2DocUtils.validate(DocumentTemplate documentTemplate, IReadOnlyQueryEnvironment queryEnvironment, Map<String, Set<IType>> types)
M2DocUtils.generate(DocumentTemplate documentTemplate, IReadOnlyQueryEnvironment queryEnvironment, Map<String, Object> variables, URI destination)

The validation is optional but this recommended when writing M2Doc templates.

For an example on how to use the code see https://github.com/ObeoNetwork/M2Doc/blob/master/tests/org.obeonetwork.m2doc.tests/src/org/obeonetwork/m2doc/test/AbstractTemplatesTestSuite.java

Hope it will help you.

**Comment by cbrun** [comment]
You might want to checkout the User guide to discover the UIs

https://github.com/ObeoNetwork/M2Doc/blob/master/plugins/org.obeonetwork.m2doc.doc/doc/user/M2Doc%20User%20Guide.textile

**Comment by AlawnWong** [comment]
3Q very much!  I am finding the way of M2DOC.

**Comment by ohaegi** [comment]
To install P2 repository, in neon you should open Install wizard in menu "Help / Install new software ...".
In this Wizard, put the url https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/M2Doc_0.9.9/repository in field "Work with :" and type entry. A M2Doc check box should appear, select it and type on "next >" button. After follow the wizard questions to finish installation.

**Comment by ohaegi** [comment]
Sorry AlawnWong ,I made a mistake,  I delete your last question.

I put it again in this comment :

 3Q very much!!!
I am finding the way of M2DOC. I will Install the 0.9.9 and try the User Guide.
Other question：
Q1:
I import all source code. Why has the problem
"An internal error occurred during: "Loading models".
The modeling project "org.obeonetwork.m2doc.ecore.wtable.test" is invalid: Problem during loading models: Error while loading representations file" ?
I use eclipse neon.
Q2:
why there is no the "org.obeonetwork.dsl.database"?
