### ISSUE TITLE
where can I get the "the database DSL"?

### ISSUE THREAD

**Issue by AlawnWong** [ObeoNetwork/M2Doc#161]
In the chapter of the Documentation generation, “To start with, M2Doc and **the database DSL** must be installed in your bundle.”

Where can I get the "the database DSL"?

**Comment by AlawnWong** [comment]
Who can tell me how to get  "the database DSL" project ?

**Comment by ylussaud** [comment]
You can find a version here: https://github.com/ObeoNetwork/InformationSystem/tree/master/models/database/plugins

But you I'm not sure it's the good version. You can have a look at other branches for different versions.

**Comment by AlawnWong** [comment]
3Q 
I will try!

**Comment by sthibaudeau** [comment]
If you just want to install the database plugins you can use the following P2 repository : 
https://www.obeo.fr/download/release/informationsystem/5.0/repository/
