### ISSUE TITLE
Which version sirius should be used in eclipse neon.2 ?

### ISSUE THREAD

**Issue by AlawnWong** [ObeoNetwork/M2Doc#163]
I use the eclipse neon.2 and sirius 4.0.0, then import the 0.9.9 source code.
why is there some problems?

**Comment by AlawnWong** [comment]
org.eclipse.sirius.diagram.ui;bundle-version="[0.0.0,4.1.0)",

**Comment by ylussaud** [comment]
You can find the version of Sirius we build against for Neon here:

http://download.eclipse.org/sirius/updates/nightly/4.0.x/neon

For other dependencies you can have a look here:

https://github.com/ObeoNetwork/M2Doc/blob/master/releng/org.obeonetwork.m2doc.targetplatforms/neon/m2doc-neon.tpd

To retrieve jar dependencies for apache POI you can run maven at the root of the repository:

mvn clean verify -Pplatform-neon,tests,updatesites

Tests are only running with AQL 5.x and Sirius 4.0.x.

**Comment by ylussaud** [comment]
An other way to have he right dependencies is to use the target platform in Eclipse:

https://github.com/ObeoNetwork/M2Doc/blob/master/releng/org.obeonetwork.m2doc.targetplatforms/neon/m2doc-neon.target

**Comment by AlawnWong** [comment]
3Q!
I use eclipse mars and Sirius 4.0.0, and then it's OK.
