### ISSUE TITLE
Runtime feature versus IDE feature

### ISSUE THREAD

**Issue by jbrazeau** [ObeoNetwork/M2Doc#166]
It would be nice to have a dedicated feature to use at runtime, that only contains what is required at runtime (probably no UI and so on).

In addition an IDE (or SDK ?) feature could include this `runtime` feature with all the tooling that is required for a developer.

Today when one only wants to use the runtime, it is not within easy reach to understand which dependencies he has to pull.

**Comment by ylussaud** [comment]
Features makes sens inside Eclipse and in this matter the IDE integration is needed for the runtime. If you need a runtime in an other context use the jar dependency to org.obeonetwork.m2doc.

**Comment by jbrazeau** [comment]
> Features makes sens inside Eclipse
True, and you can imagine somebody who may want to include m2doc runtime in its own eclipse based product but without embedding m2doc tooling plugins

**Comment by ylussaud** [comment]
The org.obeonetwork.m2doc.feature include editor... I didn't expect that :) I'll fix it.

**Comment by jbrazeau** [comment]
In addition, is `org.obeonetwork.m2doc.genconf.edit` is required at runtime ? 
Same question for 
* `org.obeonetwork.m2doc.tplconf.edit` ?
* `org.obeonetwork.m2doc.doc` ? (documentation is probably not required at runtime, no ?)
* `org.obeonetwork.m2doc.ide` ? (is it specific to IDE environment as its name sugessts ?)

**Comment by ylussaud** [comment]
I think the patch fix this issue, @jbrazeau if it's the case please close this issue, otherwise comment further problems with the feature.
