### ISSUE TITLE
`org.apache.poi` bundle  not compliant with standalone mode

### ISSUE THREAD

**Issue by jbrazeau** [ObeoNetwork/M2Doc#167]
The `org.apache.poi` bundle is built by aggregating severals jars into a dedicated OSGi bundle. This approach is OSGi compliant (but may probably nevertheless imply problems if m2doc is to be used in conjunction with another technology or framework which relies on a different version of POI).

But it is not compliant with a standalone use case in which the JVM classloader wil not be able to retrieve the included jars that are within the `org.apache.poi` bundle.

**Comment by ylussaud** [comment]
For standalone application you probably want to use original jars via maven dependencies for instance. Maven dependencies are listed in this file:

https://github.com/ObeoNetwork/M2Doc/blob/master/dependencies/org.apache.poi/pom.xml
