### ISSUE TITLE
M2Doc API dependencies on EMF

### ISSUE THREAD

**Issue by jbrazeau** [ObeoNetwork/M2Doc#168]
M2Doc API relies on EMF which is relevant as it relies on this technology. But some dependencies to EMF may be a little bit confusing for me :

* `QueryServices#registerPackages` expects an `org.eclipse.emf.common.util.EList` for the `EPackage` uri list : https://github.com/ObeoNetwork/M2Doc/blob/master/plugins/org.obeonetwork.m2doc/src/org/obeonetwork/m2doc/api/QueryServices.java#L103 ; This is probably a mistake ? `java.util.List` could probably do the work ? (it is strange at this point to have to create an EMF `BasicEList` just for a list of strings ; probably just a mistake when coding this class)
* To parse the `*.docx` element, one must provide an EMF `URI` ; I would have expected to be able to give a simple `java.io.File` or even a `java.io.InputStream` which is often more simple when you are in standalone mode ; this doesn't help to embed a template in a jar and retrieve it through the classloader (which may quickly happen if you want to build a tool that contains a document to generate whose template will not change over the time)
* As a m2doc beginner, I must admit that I feel surprise to have to give the template URI twice (for the query environment (`QueryServices#getEnvironment`) and to parse the template (`M2DocUtils#parse`). After having taken a look at the code I understand that this is because m2doc needs to be able to access to referenced resources around the template. I only want to tell that this is confusing for somebody who discovers the technology (and that tries to deal with it)

**Comment by ylussaud** [comment]
* yes that obviously a mistake
* the all purpose of this is to be able to load templates from jars, over http, or other mechanism seamlessly.
* I hope the Java doc was helpful on this issue
