### ISSUE TITLE
Generation doesn't work with Acceleo Query 5.x

### ISSUE THREAD

**Issue by cboudjennah** [ObeoNetwork/M2Doc#17]
Works with Acceleo Query 4.1 but not 5.x.

**M2Doc version:** 0.7.1
**Execution platform:** Capella 1.0.1
**POI Version:** 3.13.0

**Initial conditions:**
-M2Doc installed (+ POI 3.13.0 + Acceleo Query 5.0.x)
-1 genconf created and properly configured (the paths to the template and to the outputs are corrects, the template is existing...)

**Steps to reproduce te problem:**
-Request a generation from the genconf file

**Expected result:**
- the output file should be generated

**Actual result:**
- an error message is displayed: "The chosen operation is not currently available"

**Comment by nlepine** [comment]
fix in 0.9.1 version
M2Doc depends on AQL [5.0.0), AQL 4.0.0 is no longer supported
