### ISSUE TITLE
Add and document the ability to launch a document generation through the command line

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/M2Doc#174]
Scenarii to covers are:
- I want to launch a document generation through the command-line
- I want to launch it as part of the CI through Maven
- I want to "pre-package" a cli with my metamodels & templates to distribute it in my group.

Things to keep in mind:
- the templates are depending on the metamodels (and most likely other plugins) so we need a way to dynamically provision/install those dependencies

Since issue#82 (Standalone support) has been done implementing this ticket should not cause any specific concern.

**Comment by ylussaud** [comment]
I think this issue can be closed. @cbrun met me know if we miss something here or close this issue please.
