### ISSUE TITLE
Can I use M2DOC in the linux?

### ISSUE THREAD

**Issue by AlawnWong** [ObeoNetwork/M2Doc#176]
Can I use M2DOC in the linux?

**Comment by ylussaud** [comment]
Yes you can. All the tests are passed under Linux by the CI. You can also use it inside Eclipse or in standalone if all your Java services are standalone. It make it possible to call M2Doc from a build process for instance.

See the next release (tomorrow) for more details.

**Comment by AlawnWong** [comment]
How can i use the Source code to install the plug-ins?
When I use the Source code to run the eclipse application, some errors happened.
I think should some dependent plug-ins not be installed.
But, I don't know which dependent plug-ins should install.

**Comment by ylussaud** [comment]
If you install from the update site all dependencies should be installed.

If you want to use the sources in Eclipse you can use one of the target platforms:
https://github.com/ObeoNetwork/M2Doc/tree/master/releng/org.obeonetwork.m2doc.targetplatforms

This will set all dependencies as your target platform.

**Comment by AlawnWong** [comment]
I dont know why this error happened.
java.lang.ClassNotFoundException: org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory cannot be found by org.eclipse.xtext.ui.shared_2.10.0.v201605250459
java.lang.NoClassDefFoundError: org/eclipse/xtext/ui/guice/AbstractGuiceAwareExecutableExtensionFactory

**Comment by AlawnWong** [comment]
Error information:
!ENTRY org.eclipse.jdt.core 4 2 2017-03-16 16:36:45.472
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.core".
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in org.eclipse.xtext.ui.shared was unable to load class org.eclipse.xtext.ui.shared.internal.ExecutableExtensionFactory.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)

**Comment by ylussaud** [comment]
Your stacks a related to XText but we don't use XText in M2Doc... So I don't know. May be try to get the Modeling packaging of Eclipse. It might help with XText.

http://www.eclipse.org/downloads/packages/eclipse-modeling-tools/neon2

Hope it'll help.

**Comment by AlawnWong** [comment]
@ylussaud 
I use the linux 64-bit "eclipse-modeling-neon-2" in the ubuntu 14.04.
I install the M2Doc 0.9.9 in the Eclipse Help/Install new software/... menu.
Then, I create a "Ecore Modeling Project" and generate Model Code, Edit Code and Editor Code.
Then, I run as "Eclipse Application".
In the runtime-EclipseApplication,  I create a java project and create a class. 
Then, the error happened!

!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.core".
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in org.eclipse.xtext.ui.shared was unable to load class org.eclipse.xtext.ui.shared.internal.ExecutableExtensionFactory.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:178)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)

**Comment by AlawnWong** [comment]
@ylussaud

**Comment by AlawnWong** [comment]
@ylussaud
I want to know , How to use  this https://github.com/ObeoNetwork/M2Doc/tree/master/releng/org.obeonetwork.m2doc.targetplatforms

**Comment by ylussaud** [comment]
For your XText problem https://www.eclipse.org/forums/index.php/t/1073549/ seems to be a good starting point.

To use M2Doc you have two options. Either you are using it and don't need to change the code of M2Doc so you can use update site and don't need to bother with the target platform. Either you plan to change the source code or debug it and then you need to import the source code from the githut repository in your workspace then use a target platform. To do so open the .target and in the right top corner you have "Set as Target Platform". It should start rebuilding your workspace then you're good to go.

**Comment by AlawnWong** [comment]
@ylussaud 
I installed the version 0.10.0 using update site.
Why cannot complete the install?

Cannot complete the install because one or more required items could not be found.
  Software being installed: M2Doc 0.10.0.201703170819 (org.obeonetwork.m2doc.feature.feature.group 0.10.0.201703170819)
  Missing requirement: M2Doc IDE UI 0.10.0.201703170819 (org.obeonetwork.m2doc.ide.ui 0.10.0.201703170819) requires 'bundle org.obeonetwork.m2doc.ide [0.10.0,0.11.0)' but it could not be found
  Cannot satisfy dependency:
    From: M2Doc 0.10.0.201703170819 (org.obeonetwork.m2doc.feature.feature.group 0.10.0.201703170819)
    To: org.obeonetwork.m2doc.ide.ui [0.10.0.201703170819]

**Comment by ylussaud** [comment]
I forgot to include the plugin org.obeonetwork.m2doc.ide.ui in a feature. My bad... I let you know when a new build is ready.

**Comment by ylussaud** [comment]
There is a new release 0.10.2 the update site:
https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/0.10.2/repository/

**Comment by AlawnWong** [comment]
@ylussaud  3Q!
I have installed the 0.10.2 use this update site.  
And I find some problems.

1. In the windows, I use the template.docx to  generate the document.docx.
    I could generate the right document.docx, but M2Doc also generate the document-error.docx.
    Meanwhile, in the right document.docx, there is not any error.  Why?

2. In the Linux, I can not to generate the document.docx.  
    The error is : 
!ENTRY org.obeonetwork.m2doc.ide.ui 4 4 2017-03-20 09:47:11.146
!MESSAGE M2Doc : technical error : No valid entries or contents found, this is not a valid OOXML (Office Open XML) file
!STACK 0
org.apache.poi.openxml4j.exceptions.NotOfficeXmlFileException: No valid entries or contents found, this is not a valid OOXML (Office Open XML) file
	at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:290)
	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:774)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:344)
	at org.obeonetwork.m2doc.util.M2DocUtils.parse(M2DocUtils.java:314)
	at org.obeonetwork.m2doc.genconf.GenconfToDocumentGenerator.generate(GenconfToDocumentGenerator.java:141)
	at org.obeonetwork.m2doc.genconf.GenconfToDocumentGenerator.generate(GenconfToDocumentGenerator.java:93)
	at org.obeonetwork.m2doc.ide.ui.command.GenerateHandler.execute(GenerateHandler.java:66)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)

In my linux, I have not install openoffice.   Do you think it is the reason?
I use winscp to copy the template.docx to the linux.  Is the file format changed? 
I don't know the reason? 
So can you tell me, how to use M2DOC in the linux?

**Comment by ylussaud** [comment]
1) More validation has been added to M2Doc. Now you need to declare EPackages nsURI and variables and their types in the custom properties of the .docx template. You can use the [Dedicated pop-up editor](https://github.com/ObeoNetwork/M2Doc/blob/master/plugins/org.obeonetwork.m2doc.doc/doc/user/M2Doc%20User%20Guide.textile#dedicated-pop-up-editor) to edit custom properties on your template to fix this problem.

2) We are using apache POI to read .docx files. You should not need any thing else to use M2Doc. Maybe the file has been changed in the transfert. With scp I think it should not happen but with ftp it can happen if you didn't set the trasfert to binary. To quickly check that you can try to unzip the .docx file under linux. It will tell you if the .docx file is still a zip archive.

Unfortunately for the moment I don't know how to edit {field} with Libre Office. We are using MS Office to edit templates...

**Comment by AlawnWong** [comment]
1. If the template file is xxx.dot,  can the M2Doc  support to transform?
2. I use the binary way to transfer the  template.docx. But the error still happen.  I cann't find the reason.
    I want to know, how to use the M2Doc? I want to  try it

**Comment by ylussaud** [comment]
1) we only suppport .docx for the moment.
2) Can you unzip the  template.docx under Linux to check if it has been damaged ?

**Comment by AlawnWong** [comment]
Your mean use unzip directly to the template.docx?
like this :
unzip template.docx 
Archive:  template.docx
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of template.docx or
        template.docx.zip, and cannot find template.docx.ZIP, period.
Does this mean the file has been damaged ?

**Comment by AlawnWong** [comment]
I think the file be not damaged.
I use 7z to compress the zip in the windows , and then uncompress it in the linux.
There is not any error.
 I feel it is strange...

**Comment by ylussaud** [comment]
ca you open the template.docx in MS Word without errors ? Basically It seems like POI is not able to load the document...

**Comment by AlawnWong** [comment]
In the MS Word, the template.docx has not any errors , and the M2Doc can load and transform it.
But, in the linux , M2Doc can not load the template.docx. I try it in the ubuntu and redhat.
In your CI,  could the file load ?  Which OS is used the CI?

**Comment by AlawnWong** [comment]
I download the m2doc-linux.gtk.x86_64.zip, and want to use it to transform the template.docx.

**Comment by AlawnWong** [comment]
I find the reason that the template.docx can not be loaded.
the company security software problems.
3Q for your help.

**Comment by ylussaud** [comment]
I'm developing and testing M2Doc under Linux so Linux (Ubuntu) so I think it's not the problem. Our CI use Linux also. Not sure about the distribution, we are using travis.

For the product you need to specify a genconf model that reference your variables, the template and the output flie.

./m2doc my.genconf

You can try with the tests genconf but you will probably need to set the template and output files before using it.

**Comment by AlawnWong** [comment]
OK, 3Q!
