### ISSUE TITLE
Upgrade to Sirius 4.1

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/M2Doc#177]
M2Doc will be made compatible with Sirius 4.x (more especially 4.1) and will drop support for previous versions in the process.

**Comment by ylussaud** [comment]
merged

**Comment by cbrun** [comment]
Seems like I was too eager to upgrade AQL, the ranges are matching the version to be released.

**Comment by ylussaud** [comment]
This is fixed on master.

**Comment by ylussaud** [comment]
this is fixed on master
