### ISSUE TITLE
Does M2Doc support TableMerge operation?

### ISSUE THREAD

**Issue by nicholaskong** [ObeoNetwork/M2Doc#181]
I saw the mete-model of Template has a TableMerge element. But I did not find any description about TableMerge in User/Develop Guide document. So does M2Doc support TableMerge operation?

**Comment by RomainGuider** [comment]
Hi, 
 the TableMerge appeared to be useless because generating several contiguous tables appears like a single table (even in the case of table spawning several pages for which you wish to repeat the title line on each page). 
It remained in the meta model but may disapear in a near future!

**Comment by nicholaskong** [comment]
Ha, I see. 
But I have other question about the usage of M2Doc.
Does M2Doc support to 'Merge Cells'？ When I generate several rows which with the same name, I hope the same name or same part of Cells can be merged.

Eg:

Name | Country
---------------
AAA  | US
---------------
BBB  | CN
---------------
CCC  | CN
---------------
DDD  | US
---------------

     ||
     V

Name | Country
---------------
AAA  | US
---------------
BBB  | 
-----   CN 
CCC  | 
---------------
DDD  | US
---------------

**Comment by ylussaud** [comment]
The MergeTable has been removed from the AST see 5dd7153a7c9d5380d51410e698553e1eba2e0b33

Merged cells are not supported. So far it's not part of the road map but it could be a nice feature.

some technical input to do this:
add one or two (horizontal/vertical) options to MTable.
horizontal/vertical conflicts while merging cells ?
http://stackoverflow.com/questions/27209863/apache-poi-merge-cells-from-a-table-in-a-word-document

**Comment by ylussaud** [comment]
MCell from a MTable can now be merged horizontally or vertically. See the followinf tests and service class for more details:
- [bothMerge](https://github.com/ObeoNetwork/M2Doc/tree/master/tests/org.obeonetwork.m2doc.tests/resources/mTable/bothMerge)
- [horizontalMerge](https://github.com/ObeoNetwork/M2Doc/tree/master/tests/org.obeonetwork.m2doc.tests/resources/mTable/horizontalMerge)
- [verticalMerge](https://github.com/ObeoNetwork/M2Doc/tree/master/tests/org.obeonetwork.m2doc.tests/resources/mTable/verticalMerge)
- and the [service class](https://github.com/ObeoNetwork/M2Doc/blob/master/tests/org.obeonetwork.m2doc.tests/src/org/obeonetwork/m2doc/tests/services/MTableTestServices.java).
