### ISSUE TITLE
I find a bug about the Sirius diagram generation 

### ISSUE THREAD

**Issue by AlawnWong** [ObeoNetwork/M2Doc#182]
In the  upper left window,  right click the Generation file to Generate Documentation. The  Sirius diagram can generate correctly.
but , in the Outline and upper right window, right click the Generation file to Generate Documentation. The  Sirius diagram can not generate.
I install the 0.10.2.

**Comment by ylussaud** [comment]
I suppose the left window is the package explorer view. The outline view I also figure it out, but the "upper right windows" I'm not so sure. Do you have any stack trace or other information on what went wrong. You should check the problem view and the error log view after reproducing the bug. Add any stack trace or message related to M2Doc in this bug report please.
