### ISSUE TITLE
Concervation échelle sur l'affichage des diagrammes sirius

### ISSUE THREAD

**Issue by AntoineDelacroix** [ObeoNetwork/M2Doc#185]
Bonjour,

J'utilise m2doc pour générer un fichier word avec des diagrammes sirius:

{m:diagram descriptionId:"D_DIAG" object:"emfElement" resultKind:"oneImage" width:"200" height="200"}

Les diagrammes s'affichent mais ils ne conservent pas leurs dimensions.

En relisant la documentation il semble que les images le fasse.
J'ai vu qu'il était possible de créer des providers qui aideraient à la génération.
Malgré tout je ne suis pas sur que faire:

public double scale;
public static int maxWight = 50;
public static int maxHeight = 100;
private int widthToSet = 0;
private int heighToSet = 0;

public void setHeight(int height) {
	if (height > 0) {
		heighToSet = height;
		if (heighToSet > maxHeight) {
			heighToSet = maxHeight;
			scale = maxHeight / heighToSet;
		} else {
			heighToSet = heighToSet;
			scale = 1;
		}
 	}
}
public void setWidth(int width) {
	if(width>0){
		widthToSet = width;
		if (scale >= 1) {
			int newWidth = (int) (widthToSet * scale);
			if(newWidth<maxWight){
				widthToSet = newWidth;
			}else{
				scale = ((double)(((double)maxWight)/((double)newWidth))) * scale;
				heighToSet = (int) (getHeight()*scale);
				widthToSet =  (int) (widthToSet*scale);
			}
		} else {
			widthToSet = width;
		}
		super.setHeight(heighToSet);
		super.setWidth(widthToSet);
	}
}
soit recommandé.
Pouvez vous m'aider?

**Comment by ylussaud** [comment]
L'aspect ratio des diagrammes n'est pas conservé sur la version 0.10.x mais le problème sera corrigé pour la prochaine release 0.11.0. Le patch est deja sur la branche master si vous voulez l'essayer. Il faut laisser au moins une des deux dimension à 0 pour conserver l'aspect ratio.

**Comment by ylussaud** [comment]
Et l'implémentation de nouveau services pour Sirius dans ce commit: 44b0ee27a29c616e59dc6b097d764f58f2fe1ced
Fixe le problème.

{m:emfElement.asImageByRepresentationDescriptionName('D_DIAG').setWidth(200)}

{m:'My class diagram'.asImageByRepresentationName().setWidth(200)}

Le nom des services va peut être changer d'ici la 1.0.0. Si vous voulez tester d'ici la 0.11.0 vous pouvez utiliser l'update site nightly:

Nighlty builds (update sites):
* [master branch](https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/master/nightly/repository)
