### ISSUE TITLE
Rework the genconf editor

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/M2Doc#189]
The genconf editor is currently pretty hard to use for users:
- one need to know about Sirius, the modeling project and adding dependencies to just load the model and set the EObject parameters
- selecting an EObject to value a variable is pretty hard as this rely on the basic combo box
- properties are not documented

This ticket is about providing an editor which would be easier to use and discover, we want to avoid any requirement for managing another file (.aird), make sure that the user doesn't have to open an other view like the "properties views" in order to setup the generation, and have proper wizards to select files or EObjects.

**Comment by cbrun** [comment]
I already drafted a solution based on the EEF runtime, here is a screenshot.


![eef-properties-editor](https://cloud.githubusercontent.com/assets/582919/24900390/00299298-1ea4-11e7-9913-c57dd6d18d4b.png)

**Comment by ylussaud** [comment]
A new page has been added to the genconf editor see 32a5e1f31fd37872656598225900fdac815e8da8
