### ISSUE TITLE
Support Sirius 5.0

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/M2Doc#195]
Sirius 5.0 is being released in June as part of Oxygen.

Most impacting changes should be:
* the way representations (diagrams, trees, or tables) are managed is changed internally and might require to explicitely open/close it while doing an export
* the diagram image export is now automatically setting the output resolution to an higher level, M2doc should either rely on this or set his own strategy.

**Comment by cbrun** [comment]
It could be possible to support Sirius 5 and 4.1 at the same time, we should circle back on this using the sirius builds in May when the major changes regarding RepresentationDescritors are merged in Sirius

**Comment by ylussaud** [comment]
see above commits
