### ISSUE TITLE
Attribut dérivé

### ISSUE THREAD

**Issue by AntoineDelacroix** [ObeoNetwork/M2Doc#197]
Bonjour,

Mon modèle emf utilise des attributs dérivés.
Lors de la génération, ils ne semblent pas être détectés.
Avez vous déjà rencontré ce problème?

**Comment by ylussaud** [comment]
Bonjour,

Je pense que ça dépend de l’implémentation que vous avez de vos attributs dérivées. Le code d'AQL fait un eGet() avec le EAttribute en paramètre. Il faut voir si le code généré par EMF délègue bien vers votre implémentation.
