### ISSUE TITLE
Images in header/footer are not generated properly

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#199]
Images insertion in header/footer doesn't work. I tried to fix IDs manually in the xml to see where the problem came from, but with no success.

**Comment by flatombe** [comment]
Looks like the March 29th 2016 edit of http://stackoverflow.com/a/35103749

> POI will not save the blip reference for images in header paragraphs anymore.
> 
> /word/header1.xml:
> 
> Code compiled and run with 3.13:
> 
> `<pic:blipFill><a:blip r:embed="rId1"/>`
> 
> Same code compiled and run with 3.14:
> 
> `<pic:blipFill><a:blip r:embed=""/>`
> 

POI 3.16 might fix it.

**Comment by ylussaud** [comment]
An other problem is the size of the image. If the image is to large, it's not displayed in the header/footer. POI 3.16 fix the problem but I also has to change the test to limite the image size in order to see it in header/footer
