### ISSUE TITLE
Accentuate the differences, in the graphical editor, between Model and String definitions

### ISSUE THREAD

**Issue by flatombe** [ObeoNetwork/M2Doc#205]
Both nodes have a blue background (respectively dark for Model definitions and light for String definitions). The colors or the contrast should maybe be accentuated to help differentiate the at first sight.

**Comment by ylussaud** [comment]
A new version of this editor is being developed by @cbrun. If you have more ideas and improvements for this editor let him know.

**Comment by cbrun** [comment]
Indeed the plan is to remove this Sirius based editor and replace it with a form-based editor, you can follow and discuss in #189 to help this effort.

**Comment by ylussaud** [comment]
this editor has been replaced by a new page in the genconf editor see 32a5e1f31fd37872656598225900fdac815e8da8
