### ISSUE TITLE
Sirius-style Java service declaration instead of extension-based

### ISSUE THREAD

**Issue by flatombe** [ObeoNetwork/M2Doc#206]
Registering Java services is currently done through an Eclipse extension. This requires a runtime deployment of the plug-in contributing the services.

For ease of development of M2Doc templates, we could use a more runtime-y approach for the declaration of Java services, like in [Sirius](https://www.eclipse.org/sirius/doc/specifier/general/Writing_Queries.html#service_methods).

**Comment by ylussaud** [comment]
For the moment the registration of M2DocSiriusServices is not automatic but it will be when I'll work on the IDE and IDE UI parts of M2Doc.

There is also a ClassLoader specific to the workspace that should be used in development environment. See the Siirus ClassLoader for more details.

**Comment by ylussaud** [comment]
Maybe the answer to this bug is the property m:import:org......MyServiceClass ?

**Comment by flatombe** [comment]
Yes it seems so 👍
