### ISSUE TITLE
Erreur lors de la génération avec fichier word cible ouvert

### ISSUE THREAD

**Issue by AntoineDelacroix** [ObeoNetwork/M2Doc#211]
Bonjour,

Lorsque je génère, une erreur apparait:
" A technical error occured. please log a bug (see the error for details) "
J'ai mis un peu de temps à comprendre que le fichier word cible était ouvert...
Est ce qu'il serait possible de changer le texte de l'erreur?
![problem generation](https://cloud.githubusercontent.com/assets/15232439/25470606/381ea7e8-2b23-11e7-8874-53eeb72712cf.PNG)

**Comment by ylussaud** [comment]
Bonjour,

Est-ce que vous pouvez joindre les stacks trace de votre error log s'il vous plaît ?
