### ISSUE TITLE
Exception messages in the docx output should be more user-friendly

### ISSUE THREAD

**Issue by flatombe** [ObeoNetwork/M2Doc#214]
Currently, when there some exception happened during the generation (typically due to a Java service), the error message placed in the docx may be difficult to understand for the end user. This is for instance the case when a Sirius diagram is too large to be exported as an image, and thus a `SizeTooLargeException` is raised:

> {m: 
myEObject.asImageByRepresentationDescriptionName('MyRepresentation')
.setWidth(10).setHeight(10)
}

Results in:

> asImageByRepresentationDescriptionName(org.eclipse.emf.ecore.EObject,java.lang.String) with arguments [myEObject[TRANSIENT], MyRepresentation] failed:  Failed to execute runnable (java.lang.RuntimeException: org.eclipse.sirius.ui.tools.api.actions.export.SizeTooLargeException: MyDiagram)
Couldn't find the 'setWidth(org.eclipse.acceleo.query.runtime.impl.Nothing,java.lang.Integer)' service
Couldn't find the 'setHeight(org.eclipse.acceleo.query.runtime.impl.Nothing,java.lang.Integer)' service

Ideally, raw exceptions should never reach the output docx as such, and should rather be wrapped with a more user-friendly localizable message ; while the initial exception should still be available somewhere.

A first step could consist in encouraging Java services to provide an end-user-facing error message to such exceptions, while displaying the stacktrace in some log output and changing the currently always-generated `output-error.docx` to include the stacktrace of such exceptions.

**Comment by ylussaud** [comment]
wrong bug number...

**Comment by ylussaud** [comment]
I think the main problem here is the meaningless exception message in the first place. The stack trace has been added to the error message. Not sure it will help with the friendliness but it will be useful for service developers. For this reason I'm not in favor to suppress exceptions from the generated document.

**Comment by ylussaud** [comment]
The SizeTooLargeException come from Sirius. To avoid it you can set the Preference Sirius/Sirius Diagram "Size of exported images" to Max using the slide bar. It should fixe the issue.
