### ISSUE TITLE
It should be possible to configure a logger or an equivalent to retrieve the exceptions raised during the m2dov evaluation

### ISSUE THREAD

**Issue by jbrazeau** [ObeoNetwork/M2Doc#216]
Today, when an exception occurs in a Java service for example, you get an error message in the generated docx. Sometimes it is enough to understand and fix the problem. Sometimes it is not enough, and the full stack trace would be a great help to understand the problem.

If it was possible to add a logger in m2doc during docx generation, it would help to understand what happens. A default implementation could be binded in eclipse error log mechanism. In a standalone environment, the developer would be able to provide its own logger implementation.

**Comment by ylussaud** [comment]
Their is a new method GenerationResult.getMessages() that should keep track of info/warning/error messages. On an other hand exception stack traces are now printed in the message.

**Comment by ylussaud** [comment]
Dis the previous comment suite your needs ?

**Comment by ylussaud** [comment]
you can reopen this issue if your answer to the previous question was 'no'.
