### ISSUE TITLE
Duplicate code between TableClientProcessor and M2DocEvaluator

### ISSUE THREAD

**Issue by jbrazeau** [ObeoNetwork/M2Doc#225]
`org.obeonetwork.m2doc.generator.TableClientProcessor` and `org.obeonetwork.m2doc.generator.M2DocEvaluator` contain duplicate code, at least the following methods that appears in both classes : 
* `private void fillTable(XWPFTable table, MTable mtable)`
* `private XWPFParagraph initializeEmptyTableCell(XWPFTableCell cell, MRow row, MColumn column)`
* `private void setCellContent(XWPFTableCell cell, String text, MStyle style)`

**Comment by jbrazeau** [comment]
In addition, I've seen some test classes that look very much the same as other classes and could probabably removed (or I've missed something which is perfectly possible !!).

I am talking about the following classes : 
* `org.obeonetwork.m2doc.tests.generator.TableClientProcessorTests.TestTable` seems to be almost (or exactly ?) the same as `org.obeonetwork.m2doc.element.impl.MTableImpl`
* same for `org.obeonetwork.m2doc.tests.generator.TableClientProcessorTests.TestRow` and `org.obeonetwork.m2doc.element.impl.MTableImpl.MRowImpl`
* same for `org.obeonetwork.m2doc.tests.generator.TableClientProcessorTests.TestCell` and `org.obeonetwork.m2doc.element.impl.MTableImpl.MCellImpl`
* same for `org.obeonetwork.m2doc.tests.generator.TableClientProcessorTests.TestStyle` and `org.obeonetwork.m2doc.element.impl.MStyleImpl`

**Comment by ylussaud** [comment]
This is a temporary state. The code for diagram/table/image providers will be deleted in the next release (or so). Only use the code from the M2DocEvaluator and MElements.

**Comment by ylussaud** [comment]
bac091f6d11b40ae14add72fa71664d36bf7bdef removes the deprecated providers
