### ISSUE TITLE
Toc is not up to date after m2doc generation

### ISSUE THREAD

**Issue by nlepine** [ObeoNetwork/M2Doc#229]
Attach file for example.

with m2doc tag { TOC \o "1-3" \h \z \u }

**Comment by nlepine** [comment]
![toc](https://user-images.githubusercontent.com/3184827/28423519-8f55d560-6d6b-11e7-9388-5d3ca5ecef1a.png)

**Comment by ylussaud** [comment]
you might want to try 'newTableOfContent'.asPagination() but in order to have a ToC up to date you need to open the generated document with MS Word.

**Comment by ylussaud** [comment]
Did the previous comment worked for you ?

**Comment by ylussaud** [comment]
you can reopen this issue if your answer to the previous question was 'no'.
