### ISSUE TITLE
Refactor code which listens for extensions contributing services via IServiceHolder

### ISSUE THREAD

**Issue by flatombe** [ObeoNetwork/M2Doc#237]
The class `DeclaredServicesListener` is in plug-in org.obeonetwork.m2doc.ide. It listens for extensions implementing `IServiceHolder` to provide Java services in M2Doc templates.

However, the code instantiating this listener is in plug-in org.obeonetwork.m2doc.ide.ui, class `org.obeonetwork.m2doc.ide.ui.Activator`. The use of services through `IServiceHolder` should probably not depend on a UI plug-in.

**Comment by ylussaud** [comment]
see 25512bd32e367011afafe62cf65f9699b62c91bb
