### ISSUE TITLE
Configuration variables instantiation at generation

### ISSUE THREAD

**Issue by SamuelRochet** [ObeoNetwork/M2Doc#245]
It might be interesting to propose a instanciation mechanism of configuration variables on the fly during a generation. The idea would be to hide the configuration definition part for non-technical end users. We can imagine a selection wizard launched to the generation, etc.
It might be necessary to create 2 kinds of variables. 'Stable' variables stored in a configuration file (configuration by template creator or an advanced user) and more volatile variables varying at each generation (for end users).

**Comment by ylussaud** [comment]
You can write a [service](https://github.com/ObeoNetwork/M2Doc/blob/master/docs/doc/index.markdown#provide-new-services) to do this. And call it from a [let](https://github.com/ObeoNetwork/M2Doc/blob/master/docs/doc/index.markdown#let-example) for instance. For the 'Stable' variable we provide the [generation model](https://github.com/ObeoNetwork/M2Doc/blob/master/docs/doc/index.markdown#generation-configuration-editor) that bind variables declared in the template with their value.

On top of that you can [call M2Doc programmatically](https://github.com/ObeoNetwork/M2Doc/blob/master/docs/doc/index.markdown#using-m2doc-programmatically) to integrate generation feature to you product. For instance you can add a command and use the selection as the value of a variable.

**Comment by SamuelRochet** [comment]
Sure!
However, the vast majority of template developers will not be advanced developers. The idea would be to allow basic templates-writters (knowing how to retreive model information or how to use turnkey services but no more) to have this kind of service without having to develop it by themselves.

**Comment by ylussaud** [comment]
This might be a set of services provided directly by AQL...
