### ISSUE TITLE
No legend while exporting several diagrams with one tag

### ISSUE THREAD

**Issue by cboudjennah** [ObeoNetwork/M2Doc#25]
M2Doc version: 0.9.0
Execution platform: Capella 1.0.2
Acceleo Query version: 4.1
POI Version: 3.13.0

Initial conditions:
-M2Doc installed
-a working template without comments is used

Steps to reproduce:
-insert a tag for which several images should be exported (i.e several diagrams with the same description name on one root object . e.g:  { m:diagram provider:"org.obeonetwork.m2doc.sirius.SiriusDiagramByDiagramDescriptionNameProvider" width:"400" height:"400" legend:"Légende en dur" legendPos:"below" rootObject:"component" diagramDescriptionName:"Logical Architecture Blank" }
-generate the document and check it

Expected result:
-All the corresponding diagrams are generated
-Each diagram has the expected legend

Actual result:
-The diagrams are generated but there is no legend

**Comment by nlepine** [comment]
no legend with image tag too

**Comment by ylussaud** [comment]
providers have been removed see bac091f6d11b40ae14add72fa71664d36bf7bdef
