### ISSUE TITLE
Dynamic Style Services

### ISSUE THREAD

**Issue by SamuelRochet** [ObeoNetwork/M2Doc#250]
By default M2Doc reproduce text styles from template. It could be usefull in some cases to overwrite this template style by another one. For instance: select text color or font according a condition, apply a title level programmaticly, etc.
This should improve expressivness of generated documents but also reduce in some cases template complexity.

**Comment by ylussaud** [comment]
You can partially do that using MText. There is no way to select an other font for the moment in MStyle but you can apply modifiers like bold, italic, ...

**Comment by ylussaud** [comment]
An other issue for support of fonts has been opened #277. So I'll close this issue.
