### ISSUE TITLE
Genconf options should be validated prior to generation

### ISSUE THREAD

**Issue by ymortier** [ObeoNetwork/M2Doc#252]
For example, if the SiriusSession is invalid, the sirius services are not available and generation errors occur. It is difficult to identify the source of these errors.

Steps to reproduce, add an extra space before the uri of the SiriusSession:
`SiriusSession= ../representations.aird`

**Comment by ylussaud** [comment]
I think the validation process and generation process should be kept distinct. But we need to include the genconf validation to the validation process:

- template URI
- options (API already exists IServicesConfigurator.validate())

The M2DocSiriusServices class should be changed to warn user about the missing session at generation time.
