### ISSUE TITLE
Possibility to download a snapshot of the 1.0.0 release that contains POI

### ISSUE THREAD

**Issue by atant1** [ObeoNetwork/M2Doc#256]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
no complete snapshot for 1.0.0 Version (only sources folders)

## Expected behavior
Possibility to download snapshot for 1.0.0 release, as you can do with the release 0.9.5 for example. (for user that doesn't have internet).

**Comment by ylussaud** [comment]
I changed the build to create a zip file of the M2Doc update site. You can have a look to the zip link on the nightly update site in the [download page](http://obeonetwork.github.io/M2Doc/download/).
Unfortunately rebuilding a version 1.0.0 might have side effects on other consumer of the build. Is it possible for you to use a nightly zip ?

**Comment by ylussaud** [comment]
A [zip file](https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/1.0.0/repository.zip) has been manually added.
