### ISSUE TITLE
Double boucle for avec la même déclaration de variable

### ISSUE THREAD

**Issue by AntoineDelacroix** [ObeoNetwork/M2Doc#259]
Bonjour,

je travaille avec la version 0.10.2 depuis un fichier template.docx.
Un mauvais copier/coller m'a fait écrire ceci:

{m:for variable | elementList}
text : {m:variable .text}
    {m:for variable | elementList}
----text : {m:variable .text}
    {m:endfor}
{m:endfor}

Il en ressort
text : variable1.text
----text : variable1.text
----text : variable2.text
----text : variable3.text
text : variable2.text
----text : variable1.text
----text : variable2.text
----text : variable3.text
text : variable3.text
----text : variable1.text
----text : variable2.text
----text : variable3.text

Sur le moment je n'était pas sûr de la valeur de "variable" car elle est déclarée 2 fois sur 2 boucles for différentes.
Pouvez vous remonter une erreur en cas de multiple déclaration d'une même variable?

**Comment by ylussaud** [comment]
Pour avoir le warning il faut utiliser la validation. D'un point de vue génération cella ne pose pas de problèmes d'avoir une variable masquée. La variable ne sera masquée que pour le corps de la répétition.
Ce n'est pas judicieux de masquer des variables que ce soit dans ce cas là ou d'autres cas et c'est pour ça que l'on lève un warning à la validation. Pour ce qui est de la génération cela ne pose pas de problème.

J'ai rajouté un test pour ce cas spécifique, mais je ne pense pas que ce soit justifié de produire un warning à la génération pour ce problème.
