### ISSUE TITLE
Add pagination services

### ISSUE THREAD

**Issue by flatombe** [ObeoNetwork/M2Doc#264]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

Pagination services, ideally, should provide the means to programatically specify the document format just like you do in the WYSIWYG editor. Some of them are already included, but many are missing like the possibility to specify enumerations. For now, only static enumerations, filled with dynamic contents may be used.

## Expected behavior

M2Doc should provide a syntax for dynamic enumerations, e.g. an enumeration filled with enumerations filled with enumerations, etc. In short, what is probably missing is the "while" construct for recursion.

Limitation: there is probably a depth limitation in the WYSIWYG editors, which should also be accounted for. Maybe a specific FAQ entry to explain how many depth level can actually be used could be enough.

**Comment by ylussaud** [comment]
This could be done with services taking a String and and Integer for the text and the deph:

* asTitle()
* asBulletList()
* ...

For numbered list I guess we need an other parameter to identify the actual sequence.
For recursion we need something like a template as described in issue #125.

**Comment by ylussaud** [comment]
In fact we needed a MParagraph construct.

**Comment by ylussaud** [comment]
* Added numbering and level to MParagraph.
* Added a service to list text/table styles.
* Added a service to list numberings.
* Added setter services for MParagraph.
