### ISSUE TITLE
Add services to convert formated text into ooxml format

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#265]
It would be nice to be able to convert HTML or other formated content into ooxml to insert them direclty into the generated .docx file.

**Comment by jpequery** [comment]
for another project, we shall use docx4j-ImportXHTML, which is a docx4j extension to convert XHTML tags into ooxml. 

Note that melody contains a widget to html-format and is able to produce this kind of description. It's not the case for genuine Capella (but it can change in the future)

**Comment by ylussaud** [comment]
We need to include the URIConverter to the AQL environment for easier uses. We should also double check this statement before starting changes. I move this issue to [milestone 2.0.0](https://github.com/ObeoNetwork/M2Doc/milestone/6).

**Comment by ylussaud** [comment]
As a workaround we could strip the HTML to insert plain text. see https://polarsys.org/forums/index.php?t=rview&goto=3205#msg_3205

**Comment by ylussaud** [comment]
There is a first implementation of those services on the [nightly build](https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/master/nightly/repository) and the [documentation for HTML services](http://www.m2doc.org/ref-doc/nightly/m2doc_service_m2dochtmlservices.html).

**Comment by ylussaud** [comment]
On top of [html services](https://www.m2doc.org/ref-doc/nightly/m2doc_service_m2dochtmlservices.html), [wikitext services](https://www.m2doc.org/ref-doc/nightly/m2doc_service_m2docwikitextservices.html) have been added.
