### ISSUE TITLE
Diagram not generated because of its name

### ISSUE THREAD

**Issue by phdesanois** [ObeoNetwork/M2Doc#270]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
If the name of a diagram contains a quotation mark character("), the diagram is not generated. The following traceback is generated.

asImageByRepresentationDescriptionName(org.eclipse.emf.ecore.EObject,java.lang.String,boolean,java.util.Set) with arguments [Interaction[TRANSIENT], SD, true, [Default]] failed:  La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte java.io.IOException: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte   at java.io.WinNTFileSystem.createFileExclusively(Native Method)   at java.io.File.createTempFile(Unknown Source)   at java.io.File.createTempFile(Unknown Source)   at org.obeonetwork.m2doc.sirius.services.M2DocSiriusServices.asImage(M2DocSiriusServices.java:310)   at org.obeonetwork.m2doc.sirius.services.M2DocSiriusServices.asImage(M2DocSiriusServices.java:278)   at org.obeonetwork.m2doc.sirius.services.M2DocSiriusServices.asImageByRepresentationDescriptionName(M2DocSiriusServices.java:374)   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)   at java.lang.reflect.Method.invoke(Unknown Source)   at org.eclipse.acceleo.query.runtime.impl.JavaMethodService.internalInvoke(JavaMethodService.java:163)   at org.eclipse.acceleo.query.runtime.impl.AbstractService.invoke(AbstractService.java:136)   at org.eclipse.acceleo.query.runtime.impl.EvaluationServices.callService(EvaluationServices.java:129)   at org.eclipse.acceleo.query.runtime.impl.EvaluationServices.call(EvaluationServices.java:168)   at org.eclipse.acceleo.query.runtime.impl.EvaluationServices.callOrApply(EvaluationServices.java:204)   at org.eclipse.acceleo.query.parser.AstEvaluator.caseCall(AstEvaluator.java:192)   at org.eclipse.acceleo.query.ast.util.AstSwitch.doSwitch(AstSwitch.java:118)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.eclipse.acceleo.query.parser.AstEvaluator.caseCall(AstEvaluator.java:183)   at org.eclipse.acceleo.query.ast.util.AstSwitch.doSwitch(AstSwitch.java:118)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.eclipse.acceleo.query.parser.AstEvaluator.caseCall(AstEvaluator.java:183)   at org.eclipse.acceleo.query.ast.util.AstSwitch.doSwitch(AstSwitch.java:118)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.eclipse.acceleo.query.parser.AstEvaluator.eval(AstEvaluator.java:112)   at org.eclipse.acceleo.query.runtime.impl.QueryEvaluationEngine.eval(QueryEvaluationEngine.java:52)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseQuery(M2DocEvaluator.java:477)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseQuery(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:172)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1063)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:183)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseConditional(M2DocEvaluator.java:1083)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseConditional(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:128)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1063)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:183)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseRepetition(M2DocEvaluator.java:849)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseRepetition(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:139)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1063)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:183)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseRepetition(M2DocEvaluator.java:849)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseRepetition(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:139)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1063)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:183)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseRepetition(M2DocEvaluator.java:849)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseRepetition(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:139)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1063)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:183)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseTemplate(M2DocEvaluator.java:298)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseTemplate(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:201)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseDocumentTemplate(M2DocEvaluator.java:260)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseDocumentTemplate(M2DocEvaluator.java:1)   at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:246)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)   at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:865)   at org.obeonetwork.m2doc.generator.M2DocEvaluator.generate(M2DocEvaluator.java:253)   at org.obeonetwork.m2doc.util.M2DocUtils.generate(M2DocUtils.java:707)   at org.obeonetwork.m2doc.util.M2DocUtils.generate(M2DocUtils.java:664)   at org.obeonetwork.m2doc.genconf.GenconfUtils.generate(GenconfUtils.java:437)   at org.obeonetwork.m2doc.genconf.GenconfUtils.generate(GenconfUtils.java:370)   at org.obeonetwork.m2doc.genconf.editor.command.GenerateHandler$1.run(GenerateHandler.java:56)   at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

## Expected behavior
Generate the diagram without contraint on its name.

## Minimal reproduction of the problem with instructions
Create an ecore model and associated design model
Create a diagram with a name like : Activate the mode "simulation" on software
Create a template to export this diagram
Generaet the document :=> a traceback is displayed.

## What is the motivation / use case for changing the behavior?
To have a clear name in communication with the customer, the système architect give diagram's name with this type of characters. for instance, a sequence diagram is named
Activate the mode "simulation" on software.

## Environment

<pre><code>
M2Doc version: 1.0.0
Obeo Designer version: 9.1.2
Platform version:  Windows 7

Others:

</code></pre>

**Comment by ylussaud** [comment]
I think we miss some sanitation on the temporary file name produced by Sirius.
