### ISSUE TITLE
Loading xtext-dsl-files in genconf yields empty fields in the generated document

### ISSUE THREAD

**Issue by Tim-S** [ObeoNetwork/M2Doc#274]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

If a Xtext-DSL is used to create a model, i can load the containing dsl-file using the "Load Resource" context-menu entry as with any other xmi-Serialized model and define a variable with a reference to its contents (e.g. a variable "self" with a reference to a model-element "Greeting", which contains an attribute "name" containing a String). 

However, if i run the generation on a template accessing an attribute of the referenced model-element 
 with a field-code ((e.g. _{ m:self.name }_ ) , that field is empty in the generated document.

## Expected behavior

I expected m2doc to be able to access model-informationl from the xtext-dsl-file like i was with any xmi-backed model i have tried yet.

## Minimal reproduction of the problem with instructions

I was able to reproduce the bug using a fresh installation of 
[eclipse-modeling-tools oxygen 1a](
http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/1a/eclipse-modeling-oxygen-1a-win32-x86_64.zip).
After downloading and extracting the package, i 

1. installed Xtext through the "Install Modeling Components" wizard.
2. created a sample dsl-language as contained in  
[dslworkspace.zip](https://github.com/ObeoNetwork/M2Doc/files/1548453/dslworkspace.zip)
3. downloaded and extracted the [M2Doc 1.0.0 repository-archive](https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/1.0.0/repository.zip) und installed it through the "Install new Software" wizard
3. created a sample template and configured the genconf model in a runtime-eclipse as provided in
[runtimeworkspace.zip](https://github.com/ObeoNetwork/M2Doc/files/1548454/runtimeworkspace.zip)
4. ran the generation 
5. check the resulting generated.docx

## What is the motivation / use case for changing the behavior?

M2Doc should provide the user with the ability to use models defined by a Xtext-DSL for document-generation in the same way it does for xmi-backed models.

## Environment

<pre><code>
M2Doc version: 1.0.0
Eclipse version: 4.7.1a 64bit
Platform version:  Windows 10

Others:

</code></pre>

**Comment by Tim-S** [comment]
Seems like the reason for this behaivor are
[lines 481-482 in GenconfUtils]( https://github.com/ObeoNetwork/M2Doc/blob/master/plugins/org.obeonetwork.m2doc.genconf/src/org/obeonetwork/m2doc/genconf/GenconfUtils.java#L481)  : 
```java
 defaultResourceSet.getResourceFactoryRegistry().getExtensionToFactoryMap().put("*",
                new XMIResourceFactoryImpl());
```
If  i create  an [IConfigurationProvider](https://github.com/ObeoNetwork/M2Doc/blob/master/plugins/org.obeonetwork.m2doc.genconf/src/org/obeonetwork/m2doc/genconf/provider/IConfigurationProvider.java) 
containing
```java
@Override
	public ResourceSet createResourceSetForModels(Generation generation) {
		ResourceSet created = null;
		// If Eclipse-Platform is running, 
		// the created ResourceSet should use the global ResourceFactoryRegistry:
		if (Platform.isRunning()) {
			created = new ResourceSetImpl();
			//created.setResourceFactoryRegistry(Resource.Factory.Registry.INSTANCE);
		}
		return created;
	}
```
 and register using the corresponding extension-point in the plugin.xml
```xml
   <extension
         point="org.obeonetwork.m2doc.genconf.configuration">
      <configuration
            providerClass="m2doc.playground.providers.configuration.SomeConfigurationProvider">
      </configuration>
   </extension>
```
i can use my dsl-files and the desired information is contained in the generated document.

Maybe this can be kept in mind when resolving #268

**Comment by ylussaud** [comment]
Thanks a lot for your help. I'll change this and add a test case for Xtext models.

On the master you also have a new GenconfUtils.createResourceSetForModels() where you can give your own ResourceSet as a default value. This can be an other workaround if using M2Doc programmatically.
