### ISSUE TITLE
derived feature defined in capella metamodel are not supported

### ISSUE THREAD

**Issue by jpequery** [ObeoNetwork/M2Doc#28]
When, in an aql request, we are calling a derived feature, like componentExchanges in this case : 

{m:self.eAllContents(fa::ComponentPort).componentExchanges }

The feature is not supported, and the feature always returns an empty Set. 

It's certainly an architecture issue from capella, but it's complicated for user to create their own templates. 

There is a workaround. The user shall add the .genconf file to the sirius session using the "add model" command available on the model explorer, and then launch the document generation from the model explorer or the "capella model explorer"

**Comment by jpequery** [comment]
tested on capella 1.0.0 on windows, using M2Doc 0.7.1

**Comment by ylussaud** [comment]
AQL calls eGet(EStructuralFeature) can you check if your implementation is called from this method ?

**Comment by ylussaud** [comment]
It was a delegation issue in the generated metamodel.
