### ISSUE TITLE
Service to return diagram name

### ISSUE THREAD

**Issue by apinsonneau** [ObeoNetwork/M2Doc#282]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
Current services allow to display diagrams but not to return their name (to provide it as legend in the document).

## Expected behavior

Define a service to easilly return a diagram name.
It shall be as easy as the existing service as for example asImageByRepresentationDescriptionName('System Architecture Blank').

Moreover, in the case of a loop on existing diagrams, it shall be able to get the name of each diagram.
For example:
> m:for im | self.containedSystemAnalysis.ownedSystem.asImageByRepresentationDescr
> iptionName('System Architecture Blank')
> m:im.fit(500,400)
> [DIAGRAM NAME]
> m:endfor

## What is the motivation / use case for changing the behavior?

Provide image legend in generated documents

## Environment

<pre><code>
M2Doc version: 1.0
Eclipse version: X.Y.Z
Platform version:   X.Y.Z

Others:

</code></pre>

**Comment by ldelaigue** [comment]
For this to work in a loop, it means that the model element that represents an image should be enriched with a name (or caption, or title; And maybe some other relevant information, depending on what can be attached to diagrams and images in general, although I don't see any right now)

**Comment by ylussaud** [comment]
I added two services to get the DRepresentation itself. You can tests them using the [nightly p2 repository](https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/master/nightly/repository).

Change your template as follow:

m:for **rep** | self.containedSystemAnalysis.ownedSystem.**representationByDescriptionName**('System Architecture Blank')
**m:rep.name**
m:**rep.asImage()**.fit(500,400)
[DIAGRAM NAME]
m:endfor

The build should be ready in few minutes.
