### ISSUE TITLE
Collection not found with a correct aql request

### ISSUE THREAD

**Issue by phdesanois** [ObeoNetwork/M2Doc#287]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

Hello,
A aql request doesn't provide a collection in M2Doc context, while in the sirius interpertor it works. See sreens copy.
The reason seems to be  that some relations are empty, in your example some unitFunction haven't inputParameters.
![aql_in_m2doc](https://user-images.githubusercontent.com/33081712/39037597-3eac60c8-4481-11e8-8f57-8afdf65673ed.PNG)
![aql_in_sirius](https://user-images.githubusercontent.com/33081712/39037621-4f2f64ae-4481-11e8-86b6-a7472f6ecdc4.PNG)

## Expected behavior

We expect, in m2doc, an empty reference doesn't generate problem and provides the same result as Sirius in m2doc
## Minimal reproduction of the problem with instructions

have a meta model with reference : a->b->c->d
write a aql request which pass through several references aql:self.b.c.d
some of instance of b haven't c reference.

## Environment

<pre><code>
M2Doc version: 1.1.0
Eclipse version: 4.7.2
Platform version:  Windows 7

Others:

Thanks
Philippe
</code></pre>

**Comment by ylussaud** [comment]
Do you have this error at validation or generation ? I'm interested with the validation messages.

**Comment by ylussaud** [comment]
My guess is some metamodels haven't been resistered properly in the template. Use the [Template editor](http://www.m2doc.org/ref-doc/1.1.0/index.html#template-editor) or directly change the [Template custom properties](http://www.m2doc.org/ref-doc/1.1.0/index.html#template-custom-properties) to check or change imported metamodels.

**Comment by phdesanois** [comment]
Actually, it was a problem of registration of metamodel. This issue can be closed.
Thanks

**Comment by ylussaud** [comment]
ok thank
