### ISSUE TITLE
M2Doc for Capella should support the "Visible in documentation" field for diagrams

### ISSUE THREAD

**Issue by apinsonneau** [ObeoNetwork/M2Doc#289]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

Currently all diagrams are exported during M2Doc generation

## Expected behavior

In Capella, some diagrams can be done only to work on the model. They are not supposed to be exported for documentation. The field "Visible in documentation" could be used in order to identify such kind of diagrams by setting its value to false.

## What is the motivation / use case for changing the behavior?

Remove from documentation diagrams created only to work on the model

## Environment

<pre><code>
M2Doc version: X.Y.Z
Eclipse version: X.Y.Z
Platform version:   X.Y.Z

Others:

</code></pre>

**Comment by ylussaud** [comment]
I think this is specific to the Capella template and should be reported [here](https://github.com/ObeoNetwork/Capella-Extensions/issues).

**Comment by ylussaud** [comment]
this issue as been moved to ObeoNetwork/Capella-Extensions#16
