### ISSUE TITLE
The page count is incorrect when 'newPage'.asPagination () is set

### ISSUE THREAD

**Issue by juliendupont** [ObeoNetwork/M2Doc#300]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

In a for tag when the code  'newPage'.asPagination () is present the page count does not correspond to the number of pages. Correspond to template's number of pages.

## Minimal reproduction of the problem with instructions

**STEPS TO REPRODUCE*
In a template, add a for loop and in this for add the code newPage'.asPagination () 
In the footer add {PAGE \*MERGEFORMAT}/{NUMPAGES \*MERGEFORMAT}
Launch generation. If you have for example, 4 pages generated and that your template contains only 1 page, the result is for the 4 pages is 
1/1 
2/1 
3/1 
4/1

## Environment

<pre><code>
M2Doc version: X.Y.Z
Eclipse version: X.Y.Z
Platform version:   X.Y.Z

Others:

</code></pre>

**Comment by ylussaud** [comment]
You might want to have a look at the following tests as a workaround for this issue:

* [newPageInRepetitionWithPageCountInFooter](https://github.com/ObeoNetwork/M2Doc/tree/master/tests/org.obeonetwork.m2doc.tests/resources/paginationServices/newPageInRepetitionWithPageCountInFooter)
* [newPageInRepetitionWithPageCountInHeader](https://github.com/ObeoNetwork/M2Doc/tree/master/tests/org.obeonetwork.m2doc.tests/resources/paginationServices/newPageInRepetitionWithPageCountInHeader)
* [newPagesWithPageCountInFooter](https://github.com/ObeoNetwork/M2Doc/tree/master/tests/org.obeonetwork.m2doc.tests/resources/paginationServices/newPagesWithPageCountInFooter)
* [newPagesWithPageCountInHeader](https://github.com/ObeoNetwork/M2Doc/tree/master/tests/org.obeonetwork.m2doc.tests/resources/paginationServices/newPagesWithPageCountInHeader)
