### ISSUE TITLE
When there are "Let" tag with no "endLet" tag in a template construct, M2Doc doesn't produce any error.

### ISSUE THREAD

**Issue by ohaegi** [ObeoNetwork/M2Doc#327]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

When my docx template contains a template with a Let tag without any end let tag, the generation stop to generate document just before the template. And no error was generated. 

## What is the motivation / use case for changing the behavior?

If i launch M2Doc generartion with a docx template containing this text: 
<code>
Test1
{m:template test()}
 {m:let i='test'}
  {m:i}
{m:endtemplate}

Test2
</code>

It is just produce docx file with the Test1 text, with no any error.

## Environment

<pre><code>
M2Doc version: 2.0.2
Eclipse version: Oxygen
Platform version:   Windows

Others:

</code></pre>

**Comment by ylussaud** [comment]
This issue is related with bug #331. Let are probably not working at all.

**Comment by ylussaud** [comment]
The error message in the generation is not very accurate, but the validation add an information message that a "endlet" is missing.
