### ISSUE TITLE
Invalid expressions should return an empty string

### ISSUE THREAD

**Issue by fmadiot** [ObeoNetwork/M2Doc#334]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
When the evaluation of an AQL epression fails, the result is displayed in the generated document. While with Sirius, the result is an empty String. 

In my case, when the expression {m:person.father.name} is evaluated on a person with no father, M2Doc generates the message :

 "{m:person.father.name} Attempt to access feature (name) on a non ModelObject value (null)."

## Expected behavior
In this case I would expect an empty String, like in Sirius, when the same expression is evaluated to compute a label.

## Environment

M2Doc version: 2.0.2
Obeo Designer Community 11.1.1
Platform version:  Windows

![result](https://user-images.githubusercontent.com/2065575/53186111-a6ed9a00-3600-11e9-9435-e49ae15bd473.png)
![model](https://user-images.githubusercontent.com/2065575/53186192-cedcfd80-3600-11e9-9d1e-10f30160f3a3.png)
![generator](https://user-images.githubusercontent.com/2065575/53186193-cedcfd80-3600-11e9-86e6-79a006e3ab4c.png)

**Comment by ylussaud** [comment]
This issue is an AQL issue. I opened bug [546034](https://bugs.eclipse.org/bugs/show_bug.cgi?id=546034).

**Comment by ylussaud** [comment]
Tests above should be enabled when all our target make use of the patched version of AQL.

**Comment by ylussaud** [comment]
the AQL patch will be available in Eclipse 2019-12.
