### ISSUE TITLE
Tables are not handled correctly in templates

### ISSUE THREAD

**Issue by ldelaigue** [ObeoNetwork/M2Doc#341]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

When trying to generate a table inside a template called recursively, I get a table generated first, then the rest of text that result from the recursive invocation of the template.

## Expected behavior

I should get a table in each relevant location, not a big global table generated all in one place.

## Minimal reproduction of the problem with instructions

Use the attached template and Ecore model to reproduce
[test.zip](https://github.com/ObeoNetwork/M2Doc/files/3069517/test.zip)

## Environment

<pre><code>
M2Doc version: 3.0.0-nightly
Eclipse version: X.Y.Z
Platform version:   X.Y.Z

Others:

</code></pre>

**Comment by ylussaud** [comment]
This seem to happen when recursivity reach level 3 or more as described in bug #350.
