### ISSUE TITLE
Empty bookmark references from template constructs

### ISSUE THREAD

**Issue by dsryzhov** [ObeoNetwork/M2Doc#343]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

When bookmark reference is created in template construct it only works if template call is used after bookmark definition.

## Expected behavior

Template calls after and before bookmark definition should produce correct bookmark reference.

## Minimal reproduction of the problem with instructions

The first template call in the following code produce empty bookmark reference.

{m:template addBookmarkRefTemplate()}
{m:'Bookmark reference'.asBookmarkRef('bookmark_id')}
{m:endtemplate}

{m:addBookmarkRefTemplate()}

{m:'Some bookmark'.asBookmark('bookmark_id')}

{m:addBookmarkRefTemplate()}

## Environment

<pre><code>
M2Doc version: 2.0.2
Eclipse version: Neon
Platform version:  Windows 10

Others:

</code></pre>

**Comment by ylussaud** [comment]
There are some limitations with template constructs and bookmarks in version 2.0.2 (see #330 and #326). Those two bugs are fixed in the nightly build if you can move to the nightly as a workaround.
An other workaround is moving the bookmark after the first paragraph in the template construct. This should work at least for #330.

**Comment by dsryzhov** [comment]
Tried with 3.0 (nightly version).  The problem is the same.
The first bookmark is not resolving from template.

{}
Some bookmark
{REF bookmark_id\h}

To run this test in Capella I've modified M2Doc dependencies' versions in Capella-Extensions and installed modified version into Capella
https://github.com/ObeoNetwork/Capella-Extensions/blob/master/m2doc/org.obeonetwork.capella.m2doc.aql.queries/META-INF/MANIFEST.MF

**Comment by dsryzhov** [comment]
As I understand #330 and #326 is about creating bookmarks in template. It's not my case. I am trying to use asBokmarRef from template. Bookmark is created in the main section. 

Tried to add first paragraph befor BookmarkRef in template. The result is the same.

**Comment by dsryzhov** [comment]
I've found a workaround today and started to use .asLink() service 
{m:element.name.asLink('DocumentName.docx#' + element.id)}

This solution can be used also to create links to other documents generated from Capella libraries.
To create links to other documents I've implemented M2DOC service that calculates document's names from the project\library name.
{m:element.name.asExtLink(element)}

project\library element is obtained from element using eContainer() in a while (container != null) loop.

**Comment by ylussaud** [comment]
Thank you for your workaround, I'll double check this issue on master.

**Comment by dsryzhov** [comment]
Unfortunately this workaround does not work from templates also. {m:asLink } in template generates error. I will create another issue and provide test description later.

**Comment by dsryzhov** [comment]
Have tested your fix. It works. Thanks for quick response!

**Comment by ylussaud** [comment]
Thank you for reporting this bug.
