### ISSUE TITLE
compress images sirius diagrams in the document generated

### ISSUE THREAD

**Issue by phdesanois** [ObeoNetwork/M2Doc#344]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
A docx generated with several diagrams (+180) is very fat (600 Mo). Word cannot open this file because > 512Mo.
workaround : make 3 parts of the template, generate 3 docx, open each docx and compress all images with MSWord (200ppp). Merge the 3 docx into one. The final docx size is 40M

## Expected behavior
The  M2Doc image service could built compressed image (200ppp) to directly obtains a usable document.

## Minimal reproduction of the problem with instructions
Have a model with diagram ( sequence diagram for instance)
generate document a lot of diagram 

## What is the motivation / use case for changing the behavior?
Generate large document with several diagrams, without human handling to have a usable document.

## Environment

<pre><code>
M2Doc version: 2.0.2
ObeoTeam version: 10.1.1
Platform version:  Windows 7

Others:

</code></pre>

**Comment by ylussaud** [comment]
M2Doc is using the parameters setted for Sirius in the workspace (Sirius properties). Is it possible to change that using those properties ?
An other way to deal with that is introducing a new service on MImage to set the dpi resolution and maybe format to be able to change this from the template.

**Comment by phdesanois** [comment]
Change  property "Size of exported images" from Max to Nominal is very efficace.
Word generated size :  with Max >600Mo, with Nominal <40Mo
Conclusion : no need this new feature, perhaps add this information in M2Doc documentation.
Thank

**Comment by ylussaud** [comment]
I'll leave this open for the moment because images can come from various sources and might need such conversion.
