### ISSUE TITLE
Hyperlinks from sub-template does not work

### ISSUE THREAD

**Issue by dsryzhov** [ObeoNetwork/M2Doc#348]
Hyperlink from sub-template does not work.
Attached is the test template.

[LinkTestTemplate.docx](https://github.com/ObeoNetwork/M2Doc/files/3254007/LinkTestTemplate.docx)

**Comment by dsryzhov** [comment]
Good to know that links are also working now. I've already tested this new version. Thanks for your work!

**Comment by ylussaud** [comment]
There is no representation of hyperlink at the XWPF* level of POI A§PI. To copy it we need to go to the XML level with CT*, in order to do this we need to change the parsing and the AST in M2Doc... and of course the generation engine. Doing this will also solve issues with bookmark.

**Comment by dsryzhov** [comment]
I was forced to turn off hyperlinks generation in all element's descriptions. It complicates navigating through generated document quite a lot. 

Can you provide any information when do you plan to solve this issues?

**Comment by ylussaud** [comment]
Unfortunately to solve this issue and other related issues, I need to make deep changes to M2Doc. Such changes need to be made for a major version like the next 3.0.0. So this will be in the 3.0.0 but I can't tell when this release will happen.
