### ISSUE TITLE
Table after sirius diagrams in sub-templates

### ISSUE THREAD

**Issue by dsryzhov** [ObeoNetwork/M2Doc#349]
When representaion in sub-tempate is followed by table the representations is not added. And the following error is reported in the result document.

docDataPackageWTable(EClass=DataPkg) with arguments [org.polarsys.capella.core.data.information.impl.DataPkgImpl@6c607ffb (id: f1b99f4c-38c1-4882-87aa-40b77bbc8b3f, sid: null) (name: Media) (visibleInDoc: true, visibleInLM: true, summary: null, review: null) (visibility: UNSET)] failed:  null java.lang.NullPointerException   at org.apache.poi.xwpf.usermodel.XWPFDocument.getNextPicNameNumber(XWPFDocument.java:1510)   at org.apache.poi.xwpf.usermodel.XWPFDocument.addPictureData(XWPFDocument.java:1451)   at org.apache.poi.xwpf.usermodel.XWPFDocument.addPictureData(XWPFDocument.java:1493)   

Attached is a test template and generation result.
In the template 2 sub-templates are defined and called. One sub-template prints representations for package. Another sub-template do the same and adds table after representation. 

[DiagramTestTemplate.docx](https://github.com/ObeoNetwork/M2Doc/files/3258454/DiagramTestTemplate.docx)
[DiagramTest.docx](https://github.com/ObeoNetwork/M2Doc/files/3258455/DiagramTest.docx)

**Comment by dsryzhov** [comment]
This test was run for "In-Flight Entertainment system with M2Doc" capella model from template folder

**Comment by ylussaud** [comment]
Can you provide more line in the stack trace please ?

**Comment by dsryzhov** [comment]
You can see full stack trace in the generated document attaches in the first message ([https://github.com/ObeoNetwork/M2Doc/files/3258455/DiagramTest.docx])

**Comment by ylussaud** [comment]
I was not able to reproduce this issue with Capella extensions 5.0.0 and M2Doc 3.1.1. I think the bug might have been fixed. Feel free to reopen this issue if needed with a template for Capella 5.0.0.

I added a new Class Diagram Blank to the Media DataPackage and used the following template modified to match M2Doc extensions for Capella 5.0.0:

[DiagramTestTemplate-5.0.docx](https://github.com/ObeoNetwork/M2Doc/files/5854669/DiagramTestTemplate-5.0.docx)

**Comment by dsryzhov** [comment]
Thanks for the explanation. I will test last version.
