### ISSUE TITLE
Bookmark reference from sub-template generates runtime error

### ISSUE THREAD

**Issue by dsryzhov** [ObeoNetwork/M2Doc#351]
Bookmark reference from sub-template to bookmark created by the same sub-template in some cases generates runtime error. 

Attached to this issues is two tests. The same template is used in both tests. Different capella models with data packages is used for each test. Each capella model has several packages and classes. Mainclass has properties typed by other primitive classes. In the working test referenced class is in the same package as the MainClass. In the failed test referenced classes are from oter data packages.

1. BookmarkRefTheSamePkg.zip - working test.
2. BookmarkRefOtherPkg.zip - failed test 

[BokmarkRefOtherPkg.zip](https://github.com/ObeoNetwork/M2Doc/files/3260465/BokmarkRefOtherPkg.zip)
[BokmarkRefTheSamePkg.zip](https://github.com/ObeoNetwork/M2Doc/files/3260466/BokmarkRefTheSamePkg.zip)

**Comment by dsryzhov** [comment]
M2Doc : technical error.
org.apache.xmlbeans.impl.values.XmlValueDisconnectedException

**Comment by dsryzhov** [comment]
As a workaround now I can use asLink('generated.docx#'+element.id) to create references in the same document. As I wrote in #352 hyperlink should be colored

**Comment by ylussaud** [comment]
Is your bookmark reference is dangling as described in bug #347 ?

**Comment by dsryzhov** [comment]
No. It's working bookmark that presents in the generated document if bookmark reference is not used
