### ISSUE TITLE
{m:'link'.asLink()} with black color does not work

### ISSUE THREAD

**Issue by dsryzhov** [ObeoNetwork/M2Doc#352]
When link has black color during generation runtime error occurs.
{m:'some link'.asLink('http://www.obeo.fr')}

Template with fail
[Template.docx](https://github.com/ObeoNetwork/M2Doc/files/3260660/Template.docx)

To make template working it's enought to make link colored
[TemplateWorking.docx](https://github.com/ObeoNetwork/M2Doc/files/3260684/TemplateWorking.docx)

**Comment by ylussaud** [comment]
I don't know who it happened but in your template the RPr of the link is missing which leads to a NPE. I fixed the code. The test is based on your template since I couldn't recreate the issue from word. I guess changing the color creates the RPr (basically the style of the run).
