### ISSUE TITLE
Incompatibility with between m2doc 2.0.2 and Sirius 6.1.3

### ISSUE THREAD

**Issue by mPorhel** [ObeoNetwork/M2Doc#362]
An internal class used by M2Doc has been moved in Sirius: 

SiriusDiagramSessionEventBroker.java
```
rename from plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/SiriusDiagramSessionEventBroker.java
rename to plugins/org.eclipse.sirius.diagram/src-core/org/eclipse/sirius/diagram/business/internal/refresh/SiriusDiagramSessionEventBroker.jav
```

Bugs Sirius: 
[544347] (5.1.x)
[543651] (6.1.x)
[543651] master

This cause NoClassDefFoundError when org.obeonetwork.m2doc.sirius.services.M2DocSiriusServices.asImage(DRepresentation, boolean, Set<String>) is called if Sirius 6.1.3 is used.

See org.obeonetwork.m2doc.sirius.services.SiriusRepresentationUtils.getDDiagramToExport(DDiagram, boolean, List<Layer>, Session, boolean) which will not compile if your target platform is based on Sirius 6.1.3.

**Comment by ylussaud** [comment]
This issue is fixed in M2Doc 2.0.3 see the [download page](http://www.m2doc.org/download/).
