### ISSUE TITLE
M2doc should have canary tps/jobs/tests

### ISSUE THREAD

**Issue by mPorhel** [ObeoNetwork/M2Doc#363]
#362 could have been detected sooner. 

I see several possibilities: 

- M2Doc (nightly/maintenance) should be built on top of the latest targeted versions of Sirius : tps should reference the nighly/maintenance corresponding builds of Sirius (6.1.x, master)
- Tests should be run on those "latest" tps

**Comment by ylussaud** [comment]
Since Sirius break API on middle version number only 6.1.x and 6.2.x will be checked.
