### ISSUE TITLE
m2doc cannot run in headless mode for a Capella template

### ISSUE THREAD

**Issue by stephanelacrampe** [ObeoNetwork/M2Doc#364]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

From what I understand, there is a feature launcher missing, and when it is installed, it is still not working as an argument seems to be missing

## Environment

<pre><code>
M2Doc version: X.Y.Z
Eclipse version: X.Y.Z
Platform version:   X.Y.Z

Others:

</code></pre>

**Comment by ylussaud** [comment]
Thank you for reporting this issue. The main problem here is not the headless part. You can use Capella without a graphical environment anyway.

The issue here is not being able to run M2Doc launcher from the command line. This is a needed feature for integration with other technologies not written in Java.

**Comment by ylussaud** [comment]
After making modifications to the M2Doc launcher and installing it in Capella 1.4.0. I was not able to launch the generation without errors. I think those errors are Capella related, I mean Capella is not designed to run as part of an other product/application.

The main problem I can see in the log is the Workbench not been created and other ClassNotFoundException that can be related because some plugins can't be started without the Workbench.

**Comment by stephanelacrampe** [comment]
Thanks Yvan, seems it is not going to be easy if we want to have this feature...

**Comment by dsryzhov** [comment]
I'am able generating documents from capella model using m2doc launcher. Only sirus diagrams are not generated.  I see "Workbench has not been created yet" error in the log. 
Trying to understand how to solve this issue with an approach used in Capella xhtml command line generator. They use FakeWorkbench to load sirius models in command line application. 
I've beeing used this approach to build small app that was saving diagrams from our own sirius models to hard disk. Do you think can it be helpfull to generate m2doc models?

https://github.com/eclipse/capella-xhtml-docgen/blob/master/docgenhtml/plugins/org.polarsys.capella.docgen.commandline/src/org/polarsys/capella/docgen/commandline/HTMLCommandLine.java

**Comment by ylussaud** [comment]
Thank you for the entry point, it would be nice to be able to do headless generation.

**Comment by dsryzhov** [comment]
Today I was successfull in generating doc from capella in command line!
In the current solution m2doc launcher is not used. Instead I use capella command line extension. 
Capella has commandine application that can be extended using plugins via extension point.
There are several plugins that extend Capella command line application: validation, xhtml generation, ...  I've created a new extension for m2doc generation. To launch generation you need to launch capella with -application and -appid parameters in the following way

eclipse.exe -application org.polarsys.capella.core.commandline.core -appid rds.capella.m2doc.commandline -filepath MCInterfacesModel/genconf/MCInterfacesModel.genconf -data C:/workspace/CapellaCmd 

My M2Doc services in M2Doc templates was used correctly and Sirius diagrams was also generated.

**Comment by ylussaud** [comment]
Do you think you could contribute your capella command line extension to [M2Doc capella extensions](https://github.com/ObeoNetwork/Capella-Extensions) ?

**Comment by dsryzhov** [comment]
> Do you think you could contribute your capella command line extension to [M2Doc capella extensions](https://github.com/ObeoNetwork/Capella-Extensions) ?

Yes, I think so. I will rename plugin and pull 
current version to git (new branch) next week.

**Comment by ylussaud** [comment]
Thank you very much.

**Comment by dsryzhov** [comment]
Created pull request in Capella-extensions project with a new plugin org.obeonetwork.capella.m2doc.commandline that allows to 
This time without any documentation or feature\update site creation

To try it you need 
1. Add plugin to some updatesite
2. Install plugin to Cappella (dropins does not work in this case)
3. Create a new workspace in Capella for command line generations with all needed capella projects (with genconfs and templates)
4. Launch generation using eclipse.exe from Capella in a command line (all pathes in the commandline are defined relative to workpspace)

eclipse.exe -nosplash -consolelog -application org.polarsys.capella.core.commandline.core -appid org.obeonetwork.capella.m2doc.commandline -filepath MCInterfacesModel/genconf/MCInterfacesModel.genconf -data C:/workspace/CapellaCmd -outputfolder /MCInterfacesModel/validation -forceoutputfoldercreation

**Comment by ylussaud** [comment]
The commit on the pull request has been modified and merged.
