### ISSUE TITLE
broken document after inserting OLE Object after Table in user content

### ISSUE THREAD

**Issue by DurianGray** [ObeoNetwork/M2Doc#369]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
Word document is broken after inserting a visio document after table in user content. Strangely, it works the other way around (table after visio)
![image](https://user-images.githubusercontent.com/53748965/68559022-70013200-0476-11ea-9cb7-74173aa0d91f.png)

## Expected behavior
proper generation with given example files.

[generated.docx](https://github.com/ObeoNetwork/M2Doc/files/3829598/generated.docx)
[template.docx](https://github.com/ObeoNetwork/M2Doc/files/3829599/template.docx)
[genconf.txt](https://github.com/ObeoNetwork/M2Doc/files/3829601/genconf.txt)

## Minimal reproduction of the problem with instructions
1. generate document with attached generation configuration, template and target document
2. try changing order of table/visio document

## What is the motivation / use case for changing the behavior?
see attached files

## Environment

<pre><code>
M2Doc version: 3.0.0.201911070938
Eclipse version: 4.7.3.v20180301-0715
Capella Version: 1.3.0
Platform version: Windows 10

</code></pre>

**Comment by DurianGray** [comment]
successfully tested with 3.0.0.201911221528

**Comment by ylussaud** [comment]
good news :)
