### ISSUE TITLE
MSWord field are not always well generated

### ISSUE THREAD

**Issue by phdesanois** [ObeoNetwork/M2Doc#377]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
If a template contains an MSWord field of type "SEQ", in the generated document, certain MSWOrd fields, sometimes all of them, are generated with a fixed value and not with the MSWord field.
Consequently, if the document has a table referencing all the SEQs (for example table of figures or table of tables), the corresponding table may be empty or incomplete.

## Expected behavior
If a template has MSWord filed for instance "{ SEQ Figure | * ARABIC}", the generated document must have, for each instance, the field "{ SEQ Figure | * ARABIC}" and not "1".

## Minimal reproduction of the problem with instructions
The attached file contains a project readable with Obeo 11.1.2 and M2Doc 3.0.0 with template and generated document that shows the problem.
[pb_m2doc.zip](https://github.com/ObeoNetwork/M2Doc/files/4086271/pb_m2doc.zip)

## What is the motivation / use case for changing the behavior?
Have state-of-the-art documents with reference tables.

## Environment

<pre><code>
M2Doc version: 3.0.0
Obeo version: 11.1.0
Platform version:  Windows 7

Others:

</code></pre>

**Comment by ylussaud** [comment]
I added an option in the genconf file to update fields. By default it's set to false but you can set it to true. It update the SEQ numbers but has no effect on the table of content.

It is available in the nightly build and will be released  with M2Doc 3.1.0.
