### ISSUE TITLE
Declaration of variable of type Sequence{EClass]

### ISSUE THREAD

**Issue by adaussy** [ObeoNetwork/M2Doc#382]
## I'm submitting a...

<pre><code>
[x] Feature request

</code></pre>

## Current behavior
I would like to be able to declare a variable of type sequence. 
For exemple I would like to be able to declare a 'sections' variable of type XX:Section. This variable are injected programatically.

**Comment by ylussaud** [comment]
This works at runtime and validation, the problemehere is the type selection dialog that do no provide Sequence(...) and OrderedSet(...). They should be proposed for each available type.
