### ISSUE TITLE
representationByDescriptionName return sequence of DSemanticDiagram

### ISSUE THREAD

**Issue by phdesanois** [ObeoNetwork/M2Doc#386]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
the tempalte contains the following lines :
{m:for rep | md.representationByDescriptionName('Entities') }
 Classe => { m:rep.eClass()}
{m:rep.asImage()}
{m:endfor}

the result is 
Classe => org.eclipse.emf.ecore.impl.EClassImpl@3a1dc432 (name: DSemanticDiagram) (instanceClassName: null) (abstract: false, interface: false)
{m: rep.asImage()} Couldn't find the 'asImage(EClassifier=DSemanticDiagram)' service
 Classe => org.eclipse.emf.ecore.impl.EClassImpl@3a1dc432 (name: DSemanticDiagram) (instanceClassName: null) (abstract: false, interface: false)
{m: rep.asImage()} Couldn't find the 'asImage(EClassifier=DSemanticDiagram)' service

using the folowwing line
 
{m:for img | md.asImageByRepresentationDescriptionName('Entites')}
{m:img}
Figure 1 : { SEQ Figure | * ARABIC} : { m: md.name}
{m:endfor}

The images are displayed.

## Expected behavior

representationByDescriptionName return sequence of DRepresentation

## Minimal reproduction of the problem with instructions
Have a ecore model with an Entities diagram

I have strange behavior with the content of the test template find in https://github.com/ObeoNetwork/M2Doc/blob/master/tests/org.obeonetwork.m2doc.sirius.tests/resources/m2DocSiriusServices/representationByDescriptionName/representationByDescriptionName-template.docx .

with name attribute
{m:         <---Attempt to access feature (name) on a non ModelObject value (interface org.eclipse.sirius.viewpoint.DRepresentation).md.representationByDescriptionName('Entities')->first().name}

with sirius service
{m: md.representationByDescriptionName('Entities')->first().asImage() }Couldn't find the 'asImage(EClassifier=DSemanticDiagram)' service

## What is the motivation / use case for changing the behavior?
1) Set the diagram name in the figure legend
2) Chose the diagram to display

## Environment

<pre><code>
M2Doc version: 3.0.0
Obeo Designer Team:11.1.2
Platform version:  , Windows 7

Others:

</code></pre>

**Comment by ylussaud** [comment]
In order to manipulate DRepresentation you need to add the Sirius metamodels to your template. You can have a look at the [template property wizard](https://www.m2doc.org/ref-doc/nightly/#template-properties-wizard) and the nsURI tab on the first page.

Let me know if is solve your issue.

**Comment by phdesanois** [comment]
Add the Sirius metamodels solve the issue.
Thanks
