### ISSUE TITLE
User content that contains tables creates an error

### ISSUE THREAD

**Issue by IdaEDahl** [ObeoNetwork/M2Doc#387]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

If user content blocks (userdoc) contains a table, the first generation of a document is fine, but any re-generation adds error text in the document. "userdoc copy error : null" appears in bold red letters just above the table. The rest of the user content block is untouched, and any changes to the user content block are saved. By re-generating several times without changing anything, the message "userdoc copy error : null" is repeated as many times as the document have been re-generated. 

## Expected behavior

The error message "userdoc copy error : null" should not appear under these conditions. There is no actual error. 

## Minimal reproduction of the problem with instructions

*STEPS TO REPRODUCE*
In a working M2Doc template: 
Create a user content block (userdoc)
Create a table inside the userblock
Save
Generate a document from the template
Check that the generated document is OK; at this step everything should be normal, the table should be as defined in the template
Close the generated document
Re-generate the document - no validation error should occur
Open the re-generated document and check the userblock with the table; the error message "userdoc copy error : null" now appears in bold red letters

Test case - source code: 
![image](https://user-images.githubusercontent.com/69585786/90016225-f2d74780-dca9-11ea-8256-21ab590e4dd1.png)

First re-generation result: 
![image](https://user-images.githubusercontent.com/69585786/90016363-26b26d00-dcaa-11ea-8e55-e70dfaea2627.png)

Second re-generation with User change added:
![image](https://user-images.githubusercontent.com/69585786/90016479-5b262900-dcaa-11ea-8673-affa936fe3bb.png)

## Environment

<pre><code>
M2Doc version: 3.0.0
Eclipse version: 4.12.0
Platform version:  Windows 10 

Others:
Capella version: 1.4.0
</code></pre>

**Comment by ylussaud** [comment]
Do you have a stacktrace in the error log that could help figure out what the problem is ?

**Comment by IdaEDahl** [comment]
I have checked, but this bug does not create an entry in the error log view. I do not get any message in the console either when doing the generation. There is no validation error, so no validation document is created either. 
I forgot to mention it in the ticket, but I'm using a Capella "Extended package by Obeo" version 1.4.0. I'm not able to reproduce it in a standard Capella 1.4.0 version with M2Doc installed, even when copy/pasting the template to the new workspace.

**Comment by ylussaud** [comment]
I tried to reproduce the issue without succes. I'll try with the Capella "Extended package by Obeo". Thanks.

**Comment by ylussaud** [comment]
I don't reproduce with the Capella "Extended package by Obeo". Can you provide your template or a minimal template to reproduce the issue ?

**Comment by IdaEDahl** [comment]
This template generates the error for me. You can find it attached here:
[Test_Template.docx](https://github.com/ObeoNetwork/M2Doc/files/5075093/Test_Template.docx)
Thank you for your help!

**Comment by ylussaud** [comment]
I can't reproduce the issue. I think it's related to the edited version of the generated document. Can you provide the generated document after modification ?

**Comment by ylussaud** [comment]
I reproduced the bug. It comes from an NPE in POI when retrieving the list of used styles in the document.

**Comment by ylussaud** [comment]
The [bug repported to apache POI](https://bz.apache.org/bugzilla/show_bug.cgi?id=65099).
