### ISSUE TITLE
M2Doc validation fails to match service when using variable of type Sequence(EClassifierX)

### ISSUE THREAD

**Issue by adaussy** [ObeoNetwork/M2Doc#397]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

When using variables that are of a type Sequence(EClassierX) the M2Doc validation fails matching some services. A error is added to the template:

```
Couldn't find the 'serviceName(EClassifierLiteral=EClassierX)' service
```

It appears that the EClassifierLiteral should be mapped to an actual EClassifierType instead. The problem might from from

_org.obeonetwork.m2doc.properties.TemplateCustomProperties.getVariableTypes(AstValidator, IReadOnlyQueryEnvironment, String)_
```java
 public Set<IType> getVariableTypes(AstValidator validator, IReadOnlyQueryEnvironment queryEnvironment,
            String type) {
        final Set<IType> res = new LinkedHashSet<>();

        final AstResult astResult = parseWhileAqlTypeLiteral(queryEnvironment, type);
        final IValidationResult validationResult = validator.validate(Collections.<String, Set<IType>> emptyMap(),
                astResult);
        // TODO replace with AstValidator.getDeclarationTypes()
        final Set<IType> variableTypes = validationResult.getPossibleTypes(astResult.getAst());
        for (IType iType : variableTypes) {
            if (iType instanceof EClassifierLiteralType) {
                res.add(new EClassifierType(queryEnvironment, ((EClassifierLiteralType) iType).getType()));
            } else if (iType instanceof EClassifierSetLiteralType) {
                for (EClassifier eClassifier : ((EClassifierSetLiteralType) iType).getEClassifiers()) {
                    res.add(new EClassifierType(queryEnvironment, eClassifier));
                }
            } else {// <- Missing else if for Sequence and Set
                res.add(iType);
            }
        }

        return res;
    }
```

## Environment

<pre><code>
M2Doc version: 3.1.0
Eclipse version: 2019-06
Platform version:  Windows 10

Others:

</code></pre>

**Comment by ylussaud** [comment]
This issue has been fixed in commit 267d583890873381c17a2d0c2824bf9694356f71.
