### ISSUE TITLE
Tag endfor with variable name

### ISSUE THREAD

**Issue by vrichard12** [ObeoNetwork/M2Doc#410]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
When one accidentaly deletes an [endfor/] M2Doc only indicates that one is missing. No information is given about what loop could be incriminated. 

## Expected behavior
The proposed idea is to give possibility to tag the [endfor/] with the loop variable name. This would give enough information to the template validator to tell what loop isn't closed.

## What is the motivation / use case for changing the behavior?
Improvment of the user experience in writing M2Doc templates.

## Environment

<pre><code>
M2Doc version: 3.0.0
Eclipse version: 4.12.0
Platform version:  Windows
Others:

IS-Designer: 2.0.0
</code></pre>

**Comment by ylussaud** [comment]
The can be generalized with the header of any block being added in the error message, for instance:

`
ERROR - Invalid block: Unexpected tag m:endif at this location while parsing: m:for v | self.eClassifiers
INFO - Invalid block: Did you forget the [ENDFOR]?
`
`
ERROR - Invalid block: Unexpected tag m:endfor at this location while parsing: m:template myTemplate(a:Integer)
INFO - Invalid block: Did you forget the [ENDTEMPLATE]?
`
