### ISSUE TITLE
m:template calls generate empty lines

### ISSUE THREAD

**Issue by MS34449** [ObeoNetwork/M2Doc#418]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

In our templates there is mostly one m2doc field per line - also in template definition. Otherwise the template code would become sheer unreadable. So the general question is, when the line contains just a m2doc field and no other characters (except newline), what should m2doc do? 

It works for m:comment, which does not leave an empty line behind, but seemingly it does not work for a call to m:template which leaves behind the new line character thus effectively inserting a line into the generated document.

## Expected behavior

I think nothing should be included in the generated document in case if a call to m:template in a line of its own produces an empty string.  Or at least this behaviour should be configurable via a parameter.

## Minimal reproduction of the problem with instructions

A call to m:template in a line of its own produces an empty string (the line contains just a m2doc field and no other characters (except newline)

## What is the motivation / use case for changing the behavior?

Having a readable template which does not insert unwanted empty lines.

## Environment

<pre><code>
M2Doc version: 3.1.1
Eclipse version: 4.5.2
Platform version:   Windows Server 2012

Others:

</code></pre>

**Comment by ylussaud** [comment]
This issue is not limited to template call but to all AQL queries.
