### ISSUE TITLE
Add support for Sequence and OrderedSet variables binding in generation configuration.

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#419]
Issue #397 has added support for Sequence and OrderedSet in the M2Doc validation but we can't bind such variables in the .genconf file. We should add Definition EClasses:

* Sequence x {Model, Integer, Real, Boolean, String}
* OrderedSet x {Model, Integer, Real, Boolean, String}

**Comment by jmauersberger** [comment]
I just stumbled over this limitation yesterday! And now you fixed it, great @ylussaud
