### ISSUE TITLE
HTML ul tag is not interpreted properly by the fromHTMLBodyString() service

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#447]
In some cases hierarchical **ul** tags produce a flat output with the fromHTMLBodyString() service:
```
<p>This is an example bullet points list.</p>

<ul>
	<li>Level 1
	<ul>
		<li>Level 2
		<ul>
			<li>Level 3</li>
		</ul>
		</li>
	</ul>
	</li>
	<li>Level 1</li>
</ul>

<p>End of document.</p>
```

Produce the following flat output:

![image](https://user-images.githubusercontent.com/809511/140890225-6006ccfa-e2c8-4140-be0c-60d65cdd06a5.png)

This should also be tested with **ol** tags

**Comment by bsphane** [comment]
I have noticed also that the end of a bullet list is not always properly managed:

The following XHTML from ReqIf and Capella...
 
```
`<p>While ... are reached:</p>
<p>&nbsp;</p>
<p>&nbsp;
<blockquote>
<div>
<blockquote>
<div>
<ul>
	<li>list item 1,</li>
	<li>list item 2,</li>
	<li>list item 3,</li>
</ul>
</div>
</blockquote>
</div>
</blockquote>
Then the FCP shall (1) receive bla bla bla.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
```
`
becomes this after M2doc transformation:

![problem puces m2doc](https://user-images.githubusercontent.com/35507173/143217370-2293ae95-c543-4462-b956-607cbc4dde0a.png)

**Comment by ylussaud** [comment]
The problem here is the <li> (list item) containing a ul (unordered list).
The same problem happen here with the paragraph that start on ligne 3 and end after "Then the FCP shall (1) receive bla bla bla.".

**Comment by ylussaud** [comment]
I created the #449 issue for the missing paragraph after an **ul** of **ol** tag.
