### ISSUE TITLE
Project name contains special characters leading to the failure of generation

### ISSUE THREAD

**Issue by root-jiang** [ObeoNetwork/M2Doc#465]
[中文.zip](https://github.com/ObeoNetwork/M2Doc/files/9043496/default.zip)
Here is a Capella 5.0.0 model, with an enclosed template.
The model is named with Chinese characters, and the generation failed.

**Comment by ylussaud** [comment]
I fixed this issue c7b5c8c1a45e6f7e8f0a43d0311eece1be5b7dca
