### ISSUE TITLE
Template construct does not support Custom Service

### ISSUE THREAD

**Issue by mypsycho** [ObeoNetwork/M2Doc#467]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

Template Construct does not support the use of service provided by [IServicesConfigurator](https://github.com/ObeoNetwork/M2Doc/blob/3.2.1/plugins/org.obeonetwork.m2doc/src/org/obeonetwork/m2doc/services/configurator/IServicesConfigurator.java).
Validation fails when invocation is template construct.
On the other side, validation does not fail when used in the body of the document.

Error is due to org.eclipse.acceleo.query.runtime.impl.JavaMethodService#matches(IReadOnlyQueryEnvironment, IType[])
When iType instanceof EClassifierLiteralType, 'cls' has a wrong value.

## Expected behavior

In such case, validation should not fail and generation should be allowed.

## Minimal reproduction of the problem with instructions

- In a development platform, import [tests.m2doc.ecore.zip](https://github.com/ObeoNetwork/M2Doc/files/9182590/tests.m2doc.ecore.zip). It provides 1 service.
- In an 'Eclipse application', import [TestEcore.zip](https://github.com/ObeoNetwork/M2Doc/files/9182589/TestEcore.zip) (see attachment).
- Validate '/TestEcore/template/EcoreTestGenOk.genconf'.

## What is the motivation / use case for changing the behavior?

When a metamodel has inheritance, template construct is needed.

## Environment

<pre><code>
M2Doc version: 3.2.1
Eclipse version: 4.21.0
Platform version:   Windows 11 

Others:

Acceleo version: 3.7.11
</code></pre>

**Comment by ylussaud** [comment]
Thank you for reporting this issue. The fix seems a bit odd... This part of the code is used when providing an EClass to a service via `pkg::EClass` so the type of the element passed here is an EClass. Maybe something is missing in the initialization of the AQL interperter when evaluating a template construct...
