### ISSUE TITLE
Restart at 1 on numbered list in a template bloc does not work.

### ISSUE THREAD

**Issue by phdesanois** [ObeoNetwork/M2Doc#471]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
Set restart at 1 on numbered list in a bock template. In the generated document, the text produce ,after the second template call, does not start the number with 1.
See the generated file listnumerote.generated.docx
[listnumerote.generated.docx](https://github.com/ObeoNetwork/M2Doc/files/9665549/listnumerote.generated.docx)

## Expected behavior
Each call must be restart the number at 1.
See the expected file listnumerote.expected.docx 
[listnumerote.expected.docx](https://github.com/ObeoNetwork/M2Doc/files/9665550/listnumerote.expected.docx)

## Minimal reproduction of the problem with instructions
The provided model listnum allows to reproduce the problem by generated the document.
[listnum.zip](https://github.com/ObeoNetwork/M2Doc/files/9665568/listnum.zip)

## Environment

<pre><code>
M2Doc version: 3.2.1
OBeo team version: 11.6
Platform version:  Windows 10 Version 1809

Others:

</code></pre>

**Comment by etraisnel2** [comment]
@ylussaud This ticket should be re-opened as the issue hasn't been fixed

with this template 

<img width="722" height="460" alt="Image" src="https://github.com/user-attachments/assets/e63fab27-2d06-479a-ab1b-5027658881b5" />

I get 

<img width="482" height="499" alt="Image" src="https://github.com/user-attachments/assets/a2af90b0-c368-4f6f-93da-ac8028058074" />

Also the tests associated with the ticket have invalid expected generation results, as they expect a numbering that doesn't restart to 1
