### ISSUE TITLE
Improve documentation on the SiriusSession option

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#477]
A step by step paragraph should be added to the Capella and M2Doc documentation to set the SiriusSession option. Make sure to explain that Capella rely on Sirius in the Capella part of the documentation.

**Comment by mPorhel** [comment]
Do not hesitate to add another one (or alternative steps) to explain the corresponding steps with Team for Capella.

**Comment by ylussaud** [comment]
Also add a step by step guide to use M2Doc with Team for Capella and OD Team.
