### ISSUE TITLE
Add support for SVG.

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#482]
In last versions of MS Word, SVG are supported and add a png for backward compatibility. At the moment Apache POI doesn't support the insertion of SVG images. The idea is to convert the SVG to a PNG on when inserting SVG image with M2Doc. This is a first step until Apache POI provides support for SVG.

**Comment by ylussaud** [comment]
That's something I'm looking at. I'm trying different libraries...

**Comment by jmauersberger** [comment]
I remember that we used FreeHEP in the past but stopped using it for some reason. We currently avoid generating SVG but generate EMF/WMF directly from GMF diagrams using GDI+ (unfortunately platform specific).

**Comment by ylussaud** [comment]
Everything seems to point to the FreeHEP graphics. I'll give it a try.

**Comment by jmauersberger** [comment]
Cool. Transparency wasn't properly supported, if I remember correctly. Plus other graphical glitches.
