### ISSUE TITLE
Provide a way to override the "Size of exported images" Sirius preference

### ISSUE THREAD

**Issue by vrichard12** [ObeoNetwork/M2Doc#502]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
When generating a template, the quality of the images is subject to the "Size of exported images" Sirius preference.
When this preference is set to its maximum value, images are very large and the generated document can be disproportionately large.
Moreover, the default of this preference is at its highest value.

## Expected behavior
It would be nice to have a way to override the "Size of exported images" Sirius preferences in the genconf. 
It seems to make sense to control the quality of the images generated per template.

## Minimal reproduction of the problem with instructions
Generate any template with diagrams.

## What is the motivation / use case for changing the behavior?
The execution time is much faster when the generated images are of a reasonable size, and the generated documents are much lighter.

## Environment

<pre><code>
M2Doc version: 3.3.0
Eclipse version: Any
Platform version:  Any

</code></pre>

**Comment by ylussaud** [comment]
Two options has been added to the genconf:
* `SiriusScalingPolicy` that can be one of: WORKSPACE_DEFAULT, AUTO_SCALING, NO_SCALING, AUTO_SCALING_IF_LARGER
* `SiriusScaleLevel` and integer
