### ISSUE TITLE
Add a workspace

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#511]
This workspace should support changes (add, remove, move, and content change) from an URI.
It should also support projects. Each project will have a specific resolver responsible to resolve resources in this project and delegate the resolution to the resolver of dependency projects.

If a class is changed the workspace should invalidate the resolver and notify projects that depend on this resolver project.

It should be agnostic from the source of the change even if it will be implemented for Eclipse workspace. The listener providing the changes is in an other class.

**Comment by jmauersberger** [comment]
What is the use case behind this extension? I am just asking to understand a little better in which scenario a workspace and updates on it are used.

**Comment by ylussaud** [comment]
Oops wrong project... this issue was for [Acceleo](https://github.com/eclipse-acceleo/acceleo)
