### ISSUE TITLE
Add services to get/set document core properties.

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#512]
Core properties can be accessed using:

```
XWPFDocument.getProperties().getCoreProperties()
```
Possible services, we might not need all of them:

* setCategory(String)
* setContentStatus(String)
* setContentType(String)
* setCreated(String)
* setCreated(Optional<Date>)
* setCreator(String)
* setDescription(String)
* setIdentifier(String)
* setKeywords(String)
* setLastModifiedByUser(String)
* setLastPrinted(String)
* setLastPrinted(Optional<Date>)
* setModified(String)
* setModified(Optional<Date>)
* setRevision(String)
* setSubjectProperty(String)
* setTitle(String)
* setVersion(String)

**Comment by jmauersberger** [comment]
Very good idea. Just a minor thing: What about tags? There seems to be a field in Word for that.

**Comment by ylussaud** [comment]
maybe setKeywords() ? I didn't have a look on specific details yet.

**Comment by jmauersberger** [comment]
Seems like POIXMLProperties indeed has the functions you mentioned in your service, so seems you are right with keywords == tags. Just as an extension: may some getter properties from ExtendedProperties may make sense as well  like getHyperlinkBase() or getManager(). Anyway, all minor...

**Comment by ylussaud** [comment]
Yes, that's a good idea.
