### ISSUE TITLE
Make services like fit() in ImageServices robust against null inputs

### ISSUE THREAD

**Issue by allbutsafe** [ObeoNetwork/M2Doc#521]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
If services like .fit() are executed on "null", i.e. if the provided MImage does not exist (e.g. because of a property normally referencing diagrams is empty in this loop iteration), then an M2Doc error is provided.

## Expected behavior
These services should just not output any error, but silently not provide any output. 

## Minimal reproduction of the problem with instructions
null.fit()

## What is the motivation / use case for changing the behavior?
The proposal avoids the need to always put if clauses around e.g. .fit(), if it cannot guaranteed that an image is present.

**Comment by jmauersberger** [comment]
Accepted AND fixed in less than a day? Amazing @ylussaud !
