### ISSUE TITLE
Incorrect management of multi-level rowspan attribute

### ISSUE THREAD

**Issue by MSaguer** [ObeoNetwork/M2Doc#523]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

During table generation, rowspan attribute is correctly managed when defined in first columns
```
<table>
    <tr>
      <th>Col1</th><th>Col2</th>
      <th>Col3</th><th>Col4</th>
    </tr>
    <tr>
      <td rowspan="3">1-3</td>
      <td rowspan="3">1-3</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <td>3</td>
      <td>3</td>
    </tr>
</table>
```

Is correctly rendered by 
![image](https://github.com/ObeoNetwork/M2Doc/assets/42449441/4fbfb261-4e7d-409f-bf72-6a2cb75c6ef9) in generated doc.

But for more complex rowspan use case, cells are not correctly merged anymore
```
<table>
    <tr>
      <th></th><th>Jeff</th>
      <th>Elon</th><th>Bill</th>
      <th>Warren</th>
    </tr>
    <tr>
      <td>1</td>
      <td rowspan="5">1-5</td>
      <td rowspan="3">1-3</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <td>2</td>
      <td rowspan="3">2-4</td>
      <td>2</td>
    </tr>
    <tr>
      <td>3</td>
      <td rowspan="3">3-5</td>
    </tr>
    <tr>
      <td>4</td><td>4</td>
    </tr>
    <tr>
      <td>5</td><td>5</td><td>5</td>
    </tr>
</table>
```
is transformed into 
![image](https://github.com/ObeoNetwork/M2Doc/assets/42449441/839e31e9-94b6-4e38-b9ad-782f2133c8a2)

## Expected behavior

In second test case, expected matrix should be 
![image](https://github.com/ObeoNetwork/M2Doc/assets/42449441/dd6d3514-baf9-4a6b-8431-e6292a04ab6b)

## Minimal reproduction of the problem with instructions

See current behaviour

## Environment

<pre><code>
M2Doc version:   3.3.2.202312041107
Eclipse version:  2023-09 (4.29.0)
Platform version:   Windows

Others:

</code></pre>

**Comment by MSaguer** [comment]
Here is a simple eclipse project with input emf file based on reqif format: 
[myDoc.zip](https://github.com/user-attachments/files/15509111/myDoc.zip)

We can see the two generated arrays in template.generated.docx
![image](https://github.com/ObeoNetwork/M2Doc/assets/42449441/cc0c338f-e78a-4b7d-8679-d2da5f54f5fe)

**Comment by ylussaud** [comment]
Thank you for your inputs. I'll try to fix this issue before the next release.

**Comment by ylussaud** [comment]
Note: there is a rendering issue in LibreOffice see this [issue](https://bugs.documentfoundation.org/show_bug.cgi?id=162637) for more details.
