### ISSUE TITLE
Remove .generated temp folder for m:diagram tag 

### ISSUE THREAD

**Issue by nlepine** [ObeoNetwork/M2Doc#55]

**Comment by cbrun** [comment]
This is also quite important to have a standalone Java core which can't rely on the "project" being there any more and as such will have to rely on temporary folders.

This commit from the "standalone branch" introduce this mechanism in addition to using temporary folder and could be extracted out of the branch if this ticket needs to get fixed sooner.

https://github.com/cbrun/M2Doc/commit/dd357d09ef4ca26a846bac4849c672899b6fbf12
