### ISSUE TITLE
UI still uses the very old deprecated extension point : org.eclipse.ui.popupMenus

### ISSUE THREAD

**Issue by opcoach** [ObeoNetwork/M2Doc#6]
In the file M2Doc/plugins/org.obeonetwork.m2doc.ui/plugin.xml there is still an org.eclipse.ui.popupMenus extension that is deprecated for more than 6 or 7 years ! 

You should use org.eclipse.ui.menu, or better, an E4 model fragment that will be merged with the application model .

**Comment by RomainGuider** [comment]
Thanks for reporting this. 
We're aware of that. As the README reports, the user interface is gonna evolve with more actions and and adopt more up to date extensions. 
The org.eclipse.ui.popupMenus  extension while being deprecated stays 1-click away from being operationnal with code being generated and all. That remains pretty convenient when time's short!

**Comment by RomainGuider** [comment]
This has been fixed in the last release (0.9.0) and more actions have been implemented for more features.
