### ISSUE TITLE
can't use AQL's if in the query tag 

### ISSUE THREAD

**Issue by RomainGuider** [ObeoNetwork/M2Doc#64]
Query tags have the following form : {m:<aql expression>}. When the expression is an AQL conditionnal expression (if ... then ... else) the M2Doc parser parses m:if as a M2Doc m:if tag. 

As a consequence, the if/then/else expressions in AQL can't be used currently in M2Doc.

**Comment by ylussaud** [comment]
as a workaround you can use "m: if" it should work.
