### ISSUE TITLE
XML Schemas of extension points are not packaged

### ISSUE THREAD

**Issue by RomainGuider** [ObeoNetwork/M2Doc#68]
The extension point's schemas aren't packaged in the m2doc plugin. 
![image](https://cloud.githubusercontent.com/assets/1021936/18473899/92567526-79bf-11e6-9fb5-ca7e8856071c.png)

Looks like it should be enough to check the right box.

**Comment by nlepine** [comment]
all build properties will be clean up for 0.9.3 version
