### ISSUE TITLE
Template validation doesn't take M2Doc iteration variables declaration into acount

### ISSUE THREAD

**Issue by RomainGuider** [ObeoNetwork/M2Doc#77]
When validating a template that contains a for directive like this 
`
{m:for elt | set.elts}
  The set contains the element {m:elt.name}
{m:endfor}
`

The validation doesn't include the 'elt' variable in the set of known variables thus, it signals false errors on the for internal uses of the elt variable.

**Comment by RomainGuider** [comment]
The issue appears with AQL4 only. It's still to be fixed.

**Comment by ylussaud** [comment]
AQL 4.x is no longer supported by M2Doc
