### ISSUE TITLE
Add option 'ignoreStyles' to m:wtable tag

### ISSUE THREAD

**Issue by ldelaigue** [ObeoNetwork/M2Doc#80]
It may be useful to ignore the styles defined in Sirius when generating a table to just get a simple table without applying the Sirius styles that may not comply with the graphical design of the output document.
An option 'ignoreStyles:"true"' would be convenient for that purpose.

**Comment by ylussaud** [comment]
This tag doesn't exist anymore see MTable and services to replace this tag.
