### ISSUE TITLE
"m:diagam" tag generates a “Not found Representation” failure with Sirius 4

### ISSUE THREAD

**Issue by ohaegi** [ObeoNetwork/M2Doc#81]
The tag “m:diagram” generates a  a “Not found Representation” failure with Sirius 4
For example, if template contains : 
`m:diagram title:"'LayerTestDiagram'”`
the generated document contains :
`m:diagram title:"A problem occured while creating image from an diagram provider : Representation with title 'LayerTestDiagram' not found`

 The methods “org.obeonetwork.m2doc.sirius.providers.SiriusDiagramByTitleProvider.getAssociatedRepresentationByName(String, Session)” and “org.obeonetwork.m2doc.sirius.providers.SiriusDiagramByDiagramDescriptionNameProvider.getAssociatedRepresentationByDiagramDescriptionAndName(EObject, String, Session)”  are not compatible with SIRIUS 4  because after this version representations are not anymore contained by a DView.

We must have 2 codes to ensure Sirius 4 compatibility : 

Code for before  Sirius 4 compatibility (like it is in master branch):
```

 private DRepresentation getAssociatedRepresentationByName(String representationName, Session session) {
       if (representationName != null) {
          Collection<DRepresentation> representations = 
                  DialectManager.INSTANCE.getAllRepresentations(session);
            // Filter representations to keep only those in a selected viewpoint
           Collection<Viewpoint> selectedViewpoints = session.getSelectedViewpoints(false);
            for (DRepresentation representation : representations) {
                if (representationName.equals(representation.getName())
                   && representation.eContainer() instanceof DView) {
                    DView dView = (DView) representation.eContainer();
                   Viewpoint vp = dView.getViewpoint();
                    if (selectedViewpoints.contains(vp)) {
                        return representation;
                    }
               }
            }
        }
        return null;
    }
```

Code for after  Sirius 4 compatibility : 

```
 private DRepresentation getAssociatedRepresentationByName(String representationName, Session session) {
         if (representationName != null) {
             Collection<DRepresentationDescriptor> repDescriptors = DialectManager.INSTANCE
                     .getAllRepresentationDescriptors(session);
 
             // Filter representations to keep only those in a selected viewpoint
             Collection<Viewpoint> selectedViewpoints = session.getSelectedViewpoints(false);
 
             for (DRepresentationDescriptor dRepresentationDescriptor : repDescriptors) {
                 if (representationName.equals(dRepresentationDescriptor.getName())
                     && dRepresentationDescriptor.eContainer() instanceof DView) {
                     DView dView = (DView) dRepresentationDescriptor.eContainer();
                     Viewpoint vp = dView.getViewpoint();
                     if (selectedViewpoints.contains(vp)) {
                         return dRepresentationDescriptor.getRepresentation();
                     }
                 }
             }
         }
 
         return null;
     }
```

**Comment by cbrun** [comment]
Looks like the code only use the internal organization of "a representation might be contained in a DView" in order to filter out representations which are not in the set of the currently selected viewpoints. It might be considered to drop this extra check and then achieve transparent compatibility with the same code.

**Comment by ylussaud** [comment]
providers have been removed see bac091f6d11b40ae14add72fa71664d36bf7bdef
This code has been moved to M2DocSiriusServices
