### ISSUE TITLE
M2Doc should be able to work as a Standalone framework and be independent of File and IFile

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/M2Doc#82]
This ticket is about refactoring the core so that "out of Eclipse" and even "out of OSGi" contexts are supported. This would allow some of our products which are running server-side to leverage the M2Doc capabilities.

The core framework and the ability to launch a document generation depends on EMF, Apache POI and Guava, as such there is no reason that this aspect of the runtime would not run outside of an OSGi context.

At first glance, this would probably require to split org.obeonetwork.m2doc/ in two distinct plugins, one which has generic singleton registries and the other one which populate those registries based on the extension points.

**Comment by RomainGuider** [comment]
There's a bit more to push in the equinox-dependant plug-in that you mention : M2Doc currently uses the org.eclipse.core.resources API which requires a little bit of refactoring as well.

**Comment by cbrun** [comment]
Indeed. Widening the scope to "And should not depend on workspace or java.io.File" as after looking a bit deeper into it there doesn't seem to be a strong reason for the `org.obeonetwork.m2doc` plugin to depend on the Eclipse Workspace or even to java.io.File. Reusing the EMF URI abstraction to gather input/ouputstreams looks fairly doable and would allow for interesting deployments where the m2doc template is distributed through http, plugin:/ or even a CDO repository. 

Changing that will break the APIs though but now is the time: it will get way more complex to extract this dependency later on.

**Comment by ylussaud** [comment]
This has been fixed. The core is now standalone and not a singleton.
