### ISSUE TITLE
temporary images are not cleaned up after Sirius representation export

### ISSUE THREAD

**Issue by RomainGuider** [ObeoNetwork/M2Doc#86]
When a m:diagram tag is processed, M2Doc creates temporary files with diagram's images. These files are never erased and pollute the users's workspace.

The temporary files should be cleaned up after each generation.

**Comment by cbrun** [comment]
This is also quite important to have a standalone Java core which can't rely on the "project" being there any more and as such will have to rely on temporary folders.

This commit from the "standalone branch" introduce this mechanism in addition to using temporary folder and could be extracted out of the branch if this ticket needs to get fixed sooner.

https://github.com/cbrun/M2Doc/commit/dd357d09ef4ca26a846bac4849c672899b6fbf12
