### ISSUE TITLE
M2Doc generation and validation has no progress monitor to track progess

### ISSUE THREAD

**Issue by RomainGuider** [ObeoNetwork/M2Doc#90]
The M2Doc generation should have a progress monitor injected so that the user interface can provide some feedback on the progress to the user.

**Comment by cbrun** [comment]
A small comment which is important to keep in mind when this is done. org.eclipse.emf.common.util.Monitor should be used in the core plugin and not org.eclipse.core.runtime.IProgressMonitor in order to avoid introducing a dependency to the Eclipse platform.
