### ISSUE TITLE
An exception in the production of a diagram stops the production of the document

### ISSUE THREAD

**Issue by ldelaigue** [ObeoNetwork/M2Doc#91]
I had an exception in the treatment to produce the image of a diagram, it turned out to prevent the document generation completely.
Any exception in third-party provider sould be caught and cause the production of an error message in the output doc but it should not prevent the doc from being generated.

**Comment by ylussaud** [comment]
providers have been removed see bac091f6d11b40ae14add72fa71664d36bf7bdef
And AQL service call are exception proof
