### ISSUE TITLE
Provide a way of maintaining aspect ratio on diagrams

### ISSUE THREAD

**Issue by ldelaigue** [ObeoNetwork/M2Doc#93]
Currently it's only possible to specify the desired width/height of a diagram.
I think having a 'preserveAspectRatio' parameter would be better and could be used with either height or width.
It'd also be nice to be able to fit a diagram to the page...

**Comment by RomainGuider** [comment]
The preservation of ratio would rather be done when only one of the size parameters are used : 
- when the width only is provided, the height is computed so as to preserve the ratio
- when the height only is provided, the width is computed si as to preserve the ratio

**Comment by ylussaud** [comment]
This can be achieved by using a service returning a org.obeonetwork.m2doc.api.Image

It the image format is supported the ratio will be computed and conserved by default.

**Comment by ylussaud** [comment]
see 44b0ee27a29c616e59dc6b097d764f58f2fe1ced
