### ISSUE TITLE
Service provider registering must not be done in m2doc.ui plugin

### ISSUE THREAD

**Issue by nlepine** [ObeoNetwork/M2Doc#96]
Service provider registering is done in m2doc.ui start Activator method.
Unfortunatelly, when we do not use M2Doc UI but directly API to generate a document, services providers are never registered.
 
/*
     * (non-Javadoc)
     * 
     * @see org.eclipse.ui.plugin.AbstractUIPlugin#start(org.osgi.framework.
     * BundleContext)
     */
    @Override
    public void start(BundleContext context) throws Exception {
        super.start(context);
        plugin = this;
        Platform.getExtensionRegistry().addListener(new DeclaredServicesListener());
    }

**Comment by ylussaud** [comment]
This is now done in the org.obeonetwork.m2doc.ide plugin.
