### ISSUE TITLE
IServiceHolder and IProviderConfiguration are non-existent yet part of extension point definitions

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/M2Doc#97]
See org.obeonetwork.m2doc.configuration.exsd and org.obeonetwork.m2doc.services.register.exsd, either the extension points should be deleted or their schema should be updated with references to existing types.

**Comment by RomainGuider** [comment]
To me they IServiceHolder does exist in the org.obeonetwork.m2doc plug-in : org.obeonetwork.m2doc.services.IServiceHolder

**Comment by cbrun** [comment]
I don't see such package (with services - plural)
